### ISSUE TITLE
ValueError for no JSON object

### ISSUE THREAD

**Issue by lkursell** [biocore/biom-format#207]
"No JSON object could be decoded" is currently what is reported when a classic table is passed in place of a biom table. It would probably reduce at leas a few comments on the forum if the error message wrote:

"No JSON object could be decoded. Are you sure you're passing in a .biom table?"

@ElDeveloper: Would also be useful to somehow tell whether it's an empty file or a file in a different format and integrate this information in the error message.

**Comment by wasade** [comment]
I think the easiest thing here would be to add a more informative check into `load_table`. Basically a try/except. If we except, trigger a light investigation as to the source of the failure and report. eg:

```python
def load_table(...):
    ...
    try:
        ...
    except:
        _check_failed_load(fp)
        sys.exit(1)
    else:
        return table
```

**Comment by wasade** [comment]
I just added a unit test for this in #737, and it works out of the box so I'm in a bind as I cannot recreate this. As such, I'm removing this from the 2.1.6 milestone but am not closing it as it would be nice to have improved feedback on failed `load_table` calls.

**Comment by ElDeveloper** [comment]
I think this issue came before load_table existed.
