### ISSUE TITLE
summarize-table naming is misleading

### ISSUE THREAD

**Issue by lkursell** [biocore/biom-format#215]
given summarize_taxa provides L2, L3, etc...
wouldn't naming along the lines of "biom stats-table" be less ambiguous?

**Comment by wasade** [comment]
Do you guys feel strongly about this still? If so, please reopen. This would represent an CLI change (or at least aliasing and deprecating), and in my opinion, `summarize-table` is not inaccurate.

**Comment by mortonjt** [comment]
I agree - I think this is ok to close.
