### ISSUE TITLE
print_biom_table_summary.py

### ISSUE THREAD

**Issue by jairideout** [biocore/biom-format#269]
From @jessicalmetcalf ([original issue](https://github.com/qiime/qiime/issues/1299)):

With the older command per_library_stats.py, we had the option of passing in the mapping file and outputting a new mapping file with a column of seqs per sample. I used this all the time to create my supplemental tables for manuscripts. Can this option be added to print_biom_table_summary.py?

**Comment by wasade** [comment]
Closing as I think this would be better suited for `q2-feature-table`.
