### ISSUE TITLE
Randomly subsample samples from OTU table

### ISSUE THREAD

**Issue by josenavas** [biocore/biom-format#273]
Porting this issue from QIIME (see qiime/qiime#1385).

From @lkursell:

It would be helpful to be able to randomly subsample Samples from larger groups. For instance, if you were to compare your samples against GG or AG, etc you'd want to pull out X number of samples randomly for your comparison, and then repeat.

**Comment by wasade** [comment]
I believe this is actually already solved with `[Table.subsample(..., by_id=True)](https://github.com/biocore/biom-format/blob/2.1.5/biom/table.py#L2498)`. Please reopen if I'm wrong here
