### ISSUE TITLE
port summarize_taxa.py from QIIME

### ISSUE THREAD

**Issue by jairideout** [biocore/biom-format#276]
summarize_taxa.py needs to be ported from QIIME and made into a biom command. This port will also require some refactoring of the underlying summarize_taxa.py code to make better use of the biom `Table` API. This refactoring is mostly done in https://github.com/qiime/qiime/pull/1074.

First noted in https://github.com/qiime/qiime/issues/1402. Assigning to myself.

**Comment by wasade** [comment]
@gregcaporaso and @jairideout, is this still relevant given q2? If not, possible to close?

**Comment by gregcaporaso** [comment]
I'm fine with closing this one.
