### ISSUE TITLE
biom should check for non-numeric values, give better error message

### ISSUE THREAD

**Issue by lkursell** [biocore/biom-format#284]
One of my classic tables in Excel had "#NUM!" in the cells from a formula. When you try and convert this table with biom convert the error says:

pyqi.core.exception.CommandError: Input does not look like a classic table. Did you forget to specify that a classic table file should be created from a BIOM table file?

Seems like it would be easy enough to return a message saying that a non-numeric character is present in the table, and what it is. Tough to eye-ball in a 110x15,000 table

**Comment by wasade** [comment]
Fixed in #733
