### ISSUE TITLE
Fix `fork me` ribbon

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/biom-format#393]
The `fork me` ribbon doesn't work very well when the window is resized, see #389.

@ElBrogrammer volunteered to fix this in a later pull request.

**Comment by wasade** [comment]
Ping on this

**Comment by ElDeveloper** [comment]
Just tested this and it is no longer an issue.

**Comment by wasade** [comment]
@ElDeveloper, I believe you left this out of your comment:

![](https://dmiessler.cachefly.net/images/Screen-Shot-2014-01-03-at-2.22.51-AM.png)

**Comment by ElDeveloper** [comment]
Indeed!!
