### ISSUE TITLE
include default datasets

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#461]
Smaller ones, like Costello whole body and 88 soils perhaps. This should be implemented similar to scikit-learn. Eg

``` python
from biom import datasets
costello = datasets.load_costello()
soils = datasets.load_88soils()
```

Tables should include full metadata

**Comment by wasade** [comment]
I'd still really like to have this. The basic example table is nice but so limited. But, the dataset tables should be small (few MB tops) to not bloat the repo too much.

@josenavas and @antgonza , the qiita load from URL isn't feasible for a while, right? 

A URL load would be nice but not necessary to resolve this issue.

**Comment by antgonza** [comment]
Not yet ...

**Comment by josenavas** [comment]
Not from Qiita - but we can make a couple of this available through the FTP so at least we can make the dataset available and change internally the URL later once Qiita exposes the interface. What do you think?

**Comment by wasade** [comment]
Closing as this is more under the scope of `redbiom`
