### ISSUE TITLE
Create method to add more data (observation and samples)

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/biom-format#475]

**Comment by wasade** [comment]
@ElDeveloper, I think that #720 resolves this? Please reopen if necessary

**Comment by ElDeveloper** [comment]
👍!!

**Comment by ElDeveloper** [comment]
Though, just noticed the PR hasn't been merged 🤔

**Comment by wasade** [comment]
meh. Want to resolve that problem??? :)
