### ISSUE TITLE
What biom version?

### ISSUE THREAD

**Issue by maasha** [biocore/biom-format#558]
I can't find a way to get `biom` to tell what version it is? I have tried `biom` and `biom --version`, etc.

`pip freeze` shows me `biom-format==2.1`, but that is really not optimal.

**Comment by mortonjt** [comment]
Is it safe to close this issue?

I'm able to run the following just fine
```
>>> import biom
>>> biom.__version__
'2.1.2'
```

**Comment by ElDeveloper** [comment]
This issue is referring to users not being able to call `biom
--verison`. Current workaround is to call a subcommand with that flag
`biom summarize-table --version`.

**Comment by mortonjt** [comment]
Yeah, I deleted my comment after realizing that.  Thanks for clearing that up.

**Comment by ElDeveloper** [comment]
No problemo!

**Comment by jairideout** [comment]
Fixed in #655.
