### ISSUE TITLE
certain versions of HDF5 result in failure when trying to write a biom table with all zeros

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/biom-format#581]
We discovered this issue when building/testing the QIIME 1.9.0 AMI when some QIIME rarefaction tests failed (biocore/qiime#1836). When loading a table with all zero values, but with both ``len(sample_ids) > 0`` and ``len(observations_ids) > 0``, writing that table fails with HDF5 1.8.4, but not with HDF5 1.8.14.

We're addressing this for QIIME by modifying the tests. Since a table of all zeros is a boundary case that is not likely to be hit often (if ever) in practice, the code fails noisily when the case is hit, and there is a work-around by upgrading the HDF5 version, we're ok with this solution for QIIME 1.9.0. We wanted to post here so we have a record in case any users run into the error below in the future. The failure below occurs with h5py 2.4.0 and HDF5 1.8.4, but not with h5py 2.4.0 and HDF5 1.8.14 (we didn't check with any intermediate versions of HDF5). 

The fix for this might be to just require HDF5 >= 1.8.14. 

```python
In [1]: import numpy as np
In [2]: from biom.table import Table
In [4]: data = np.zeros(40).reshape(10, 4)
In [5]: sample_ids = ['S%d' % i for i in range(4)]
In [6]: observ_ids = ['O%d' % i for i in range(10)]
In [7]: table = Table(data, observ_ids, sample_ids, table_id='Example Table')
In [11]: from biom.util import biom_open
In [12]: with biom_open('example.biom', 'w') as biom_file:
   ....:     table.to_hdf5(biom_file, "no one")
   ....:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-802efaa59a08> in <module>()
      1 with biom_open('example.biom', 'w') as biom_file:
----> 2     table.to_hdf5(biom_file, "no one")
      3

/usr/local/lib/python2.7/dist-packages/biom/table.pyc in to_hdf5(self, h5grp, generated_by, compress)
   3479                   self.ids(axis='observation'),
   3480                   self.metadata(axis='observation'),
-> 3481                   self.group_metadata(axis='observation'), 'csr', compression)
   3482         axis_dump(h5grp.create_group('sample'), self.ids(),
   3483                   self.metadata(), self.group_metadata(), 'csc', compression)

/usr/local/lib/python2.7/dist-packages/biom/table.pyc in axis_dump(grp, ids, md, group_md, order, compression)
   3359                                dtype=np.float64,
   3360                                data=self._data.data,
-> 3361                                compression=compression)
   3362             grp.create_dataset('matrix/indices', shape=(len_data,),
   3363                                dtype=np.int32,

/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.pyc in create_dataset(self, name, shape, dtype, data, **kwds)
     97         """
     98         with phil:
---> 99             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    100             dset = dataset.Dataset(dsid)
    101             if name is not None:

/usr/local/lib/python2.7/dist-packages/h5py/_hl/dataset.pyc in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
    112     if maxshape is not None:
    113         maxshape = tuple(m if m is not None else h5s.UNLIMITED for m in maxshape)
--> 114     sid = h5s.create_simple(shape, maxshape)
    115
    116

/usr/local/lib/python2.7/dist-packages/h5py/_objects.so in h5py._objects.with_phil.wrapper (/tmp/pip-build-8Ijz6u/h5py/h5py/_objects.c:2405)()

/usr/local/lib/python2.7/dist-packages/h5py/_objects.so in h5py._objects.with_phil.wrapper (/tmp/pip-build-8Ijz6u/h5py/h5py/_objects.c:2362)()

/usr/local/lib/python2.7/dist-packages/h5py/h5s.so in h5py.h5s.create_simple (/tmp/pip-build-8Ijz6u/h5py/h5py/h5s.c:1353)()

ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)
```

**Comment by jairideout** [comment]
Thanks @gregcaporaso! Note that since HDF5 1.8.14 is the latest version, we probably don't want to require users to have this version, since that's fairly restrictive. This bug seems to be fixed in 1.8.13, though I'm not sure what version it was actually fixed in.

BIOM devs, is someone available to look into this further and perhaps post an issue on the h5py tracker? It might be a bug in h5py since they support HDF5 1.8.4.

**Comment by ElDeveloper** [comment]
I've opened an issue in h5py's tracker describing this problem, see here https://github.com/h5py/h5py/issues/525 .

**Comment by ElDeveloper** [comment]
We actually just got a reply from one of the h5py maintainers who suggested upgrading to at least 1.8.7 (where this bug was fixed in HDF5, see this [link](http://hdfgroup.org/ftp/HDF5/prev-releases/ReleaseFiles/release5-187), look under the library section).

**Comment by jairideout** [comment]
@ElDeveloper thanks for looking into this!
