### ISSUE TITLE
definition of "empty" biom table differs 

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/biom-format#582]
There are two different definitions for "empty" for a `Table` object.

[The first](https://github.com/biocore/biom-format/blob/master/biom/err.py#L8) is if a table has all zero values, and [the second](https://github.com/biocore/biom-format/blob/master/biom/table.py#L1237) is if a table has either no sample ids or no observation ids. It's not immediately clear to @jairideout and I which of these is the better definition, but these should be unified.

**Comment by jairideout** [comment]
:+1:, it looks like the former definition is assumed in QIIME's rarefaction code (see [this line](https://github.com/biocore/qiime/blob/master/qiime/rarefaction.py#L173) and https://github.com/biocore/qiime/issues/1836 for more details), but the BIOM code uses the latter definition.

**Comment by wasade** [comment]
@gregcaporaso or @jairideout, can I assign either of you this for the pending minor bugfix release?

**Comment by jairideout** [comment]
I'm not comfortable working on this because I'm not sure how this will affect backwards-compatibility with QIIME or what the correct definition of "empty" is in the context of BIOM. This may be better to define when `Table` is ported to scikit-bio.

**Comment by wasade** [comment]
Sounds good, thanks

**Comment by wasade** [comment]
This is actually a documentation issue. The references cited in the seed for this issue are actually consistent in the behavior of the code as `err` performs its [check](https://github.com/biocore/biom-format/blob/master/biom/err.py#L78) against `Table.is_empty()`.
