### ISSUE TITLE
inconsistent representation of missing/null metadata

### ISSUE THREAD

**Issue by jairideout** [biocore/biom-format#585]
If a BIOM JSON file is missing metadata along an axis, it is represented as `None`. With BIOM HDF5, missing metadata is represented as an empty `defaultdict`.

For example, I generated a file in QIIME in both formats using `summarize_taxa.py`. The following output differs when running `biom summarize-table` on both tables:

JSON:

```
...
Sample Metadata Categories: None provided
Observation Metadata Categories: None provided
...
```

HDF5:

```
...
Sample Metadata Categories:
Observation Metadata Categories:
...
```

Loading both tables into memory yields objects that are not equal due to different null metadata:

```python
In [1]: from biom import load_table

In [2]: t1 = load_table('qiime_overview_tutorial/taxa_summary/otu_table_L3.biom') # JSON

In [3]: t2 = load_table('h5py_qiime_tutorial/qiime_overview_tutorial/taxa_summary/otu_table_L3.biom') # HDF5

In [4]: t1 == t2
Out[4]: False

In [5]: t1.descriptive_equality(t2)
Out[5]: 'Observation metadata are not the same'

In [6]: t1.metadata(axis='observation')

In [7]: t2.metadata(axis='observation')
Out[7]:
(defaultdict(<function <lambda> at 0x10e7098c0>, {}),
 defaultdict(<function <lambda> at 0x10e709938>, {}),
 defaultdict(<function <lambda> at 0x10e7099b0>, {}),
 defaultdict(<function <lambda> at 0x10e709a28>, {}),
 defaultdict(<function <lambda> at 0x10e709aa0>, {}),
 defaultdict(<function <lambda> at 0x10e709b18>, {}),
 defaultdict(<function <lambda> at 0x10e709b90>, {}),
 defaultdict(<function <lambda> at 0x10e709c08>, {}),
 defaultdict(<function <lambda> at 0x10e709c80>, {}),
 defaultdict(<function <lambda> at 0x10e709cf8>, {}),
 defaultdict(<function <lambda> at 0x10e709d70>, {}),
 defaultdict(<function <lambda> at 0x10e709de8>, {}),
 defaultdict(<function <lambda> at 0x10e709e60>, {}))
```

**Comment by ElDeveloper** [comment]
@josenavas, I could be wrong but I think you are were the person who worked on adding metadata support to BIOM during the HDF5 transition. Would you mind looking into this?

**Comment by josenavas** [comment]
I can take a look into this, not until next week though...

**Comment by ElDeveloper** [comment]
Ok, thanks!

**Comment by ElDeveloper** [comment]
@josenavas, I was talking offline with @jairideout and he mentioned that the Flagstaff team is hoping to have the next release of QIIME by Friday Jan 30th, do you think you'll have a chance to have a look before then so a new biom release can be prepared accordingly?

@wasade if we get this and #584 solved, do you have 10-15 minutes to do a biom release? I could call you on Skype and we can coordinate. Note that I'm gonna be moving to San Diego on Friday so I'll have very  limited e-mail access for a few days.

**Comment by josenavas** [comment]
Uhm... a bit difficult given the EMP issues that we have been seeing lately. If I can find that issue today, I can start working on this tomorrow. I can give an update tonight to see if I'll be able to work on this or not. Sorry about this!

**Comment by ElDeveloper** [comment]
Thanks, yeah I know there's plenty of other things going on, specially
with the move, etc. Thanks for the update, let me know if there's
anything I can help with.

**Comment by jairideout** [comment]
@josenavas do you have an update on when you'll be able to work on this? Thanks!

**Comment by wasade** [comment]
Can't do anything until Feb 2 at the earliest, sorry

**Comment by gregcaporaso** [comment]
@jairideout and I could do the release if @josenavas can fix the bug, and if you guys can give us notes on the steps for the BIOM release. We're *really* hoping to get the QIIME release out this Friday, and this would be blocking. (Completely understand that everyone is super-busy right now - just trying to figure out how we can wrap up the QIIME release ASAP.)

**Comment by Jorge-C** [comment]
Hey, I can find some time to track this (and #588 too) today or tomorrow so that the biom/qiime releases are possible. Any other blocking issues?

**Comment by gregcaporaso** [comment]
Not that we know of, thanks so much for the help with this @Jorge-C!

**Comment by ElDeveloper** [comment]
Thanks @Jorge-C

**Comment by josenavas** [comment]
Thanks @Jorge-C 
It would be great if you can start with #588, I'm going to start working on this in ~30min.
Sorry for the late reply, quite a busy day today...

**Comment by Jorge-C** [comment]
No problem, this is all yours now but let me know if something comes up and
you get even busier :)

2015-01-27 15:19 GMT-07:00 josenavas <notifications@github.com>:

**Comment by wasade** [comment]
Greg, bump version numbers, add change log mention, tag, do sdist (test
it), then sdist upload, finally push tag.

Then, switch to ghpages, build doc, push

Last bump versions to dev, update change log, push

I don't think there are compiled notes anywhere
