### ISSUE TITLE
`is-json` cmd line option

### ISSUE THREAD

**Issue by Jorge-C** [biocore/biom-format#591]
From Jai:
> What is the purpose of `--is-json`? It seems silly to have to tell the script what the underlying file format is of a file that you're trying to validate (most users won't know what this is). Perhaps this option could be removed?

I don't see the reason to keep it either.

**Comment by wasade** [comment]
Was added for sake of being explicit, no problem to drop

**Comment by wasade** [comment]
@Jorge-C, would this be quick to resolve?

**Comment by Jorge-C** [comment]
I didn't investigate it, but I can have a look while updating for the newest pep8 cheks later today (unless someone has time to do it earlier).

**Comment by wasade** [comment]
im doing pep8 right now, thanks though! that would be awesome if you could
get this knocked out!
