### ISSUE TITLE
Feature Request: multiple observation metadata columns when converting to classic format

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [biocore/biom-format#597]
Currently, one can specify which observation metadata column is appended to the classic table through the option --header-key.  However, if multiple observation metadata columns exist, one is forced to choose only one to keep; it'd be nice to be able to provide a comma-separated list to the --header-key option to convert multiple observation metadata columns.

**Comment by mdehollander** [comment]
I run into this limitation when converting to tsv. So it would be great if support for multiple observations data columns in the tsv format is supported. Are there any plans to implement this?

**Comment by wasade** [comment]
It isn't planned right now, but I'll raise this with the development team. It's possible that if this does go forward that we'd hold off work until the `Table` is ported to scikit-bio.

**Comment by gregcaporaso** [comment]
Yes, I think we'd want to wait until the readers/writers are in scikit-bio for this. I think this will be the next object that we work on for scikit-bio.

**Comment by wasade** [comment]
Closing as deferred to skbio.
