### ISSUE TITLE
Table.to_hdf5 was not formatting COG_Category correctly

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#608]
The formatters for the metadata are [hardcoded](https://github.com/biocore/biom-format/blob/master/biom/table.py#L3471) such that, if a key that corresponds to a hardcoded formatter is not found, it will default to the general formatter. This means that `vlen_list_of_str_formatter` is only accessible for the hardcoded types. This should be parameterized, however, that introduces an API change. 

The quick fix here is to allow a hardcoding for "COG_Category". The better fix requires expanding out the `to_hdf5` method resulting in an API change.

cc @gregcaporaso @jairideout regarding API change or quick fix. I'm leaning on quick fix...

**Comment by wasade** [comment]
This also includes 'KEGG_Description'.

**Comment by wasade** [comment]
Actually, KEGG description is worse as it is a list of list of string. AFAIK we don't currently have support within the hdf5 formatters or parsers

**Comment by wasade** [comment]
UGH. This impacts KEGG_Pathways as well.

**Comment by josenavas** [comment]
@wasade KEGG_Pathways should be supported, as there is a formatter for them [here](https://github.com/biocore/biom-format/blob/master/biom/table.py#L3473)

**Comment by wasade** [comment]
The formatter is wrong

**Comment by wasade** [comment]
The formatter is for `['foo', 'bar']`, however, the pathway data is encoded as `[['foo', 'bar'], ['1', '2']]`

**Comment by josenavas** [comment]
ooops, sorry. I was unfamiliar with that data...

**Comment by gregcaporaso** [comment]
I think you should go with the quick fix here. We can get a better fix in place for a future iteration. Backward compatibility is what's most important in the 2.1.x cycle.

**Comment by wasade** [comment]
@gregcaporaso, I put in a more general solution that does introduce a new default kwarg, but it won't impact existing use as it requires explicitly using the kwarg to change behavior
