### ISSUE TITLE
BIOM file format 2.0 extension proposal

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#612]
`biom summarize-table` stats should already be retained within the table. The primary expense with computing this calculation is when loading the table, and it is an extremely common operation. Thus, the proposal is to add these stats at write. This can be done in a backward compatible way with BIOM Format 2.0 such that we just add attributes to the format. It would be a good idea to mark as BIOM Format 2.1, however a BIOM 2.1 table would be compatible with anything consuming 2.0.

The specific attributes being proposed at the `/` level are:
- `n_samples` : the number of samples
- `n_observations` : the number of observations
- `density` : the table density 
- `sample_histogram_counts` : counts of non-zero observations per sample, suggest 10 bins
- `sample_histogram_bins` : bin edges for the observations per sample histogram
- `observation_histogram_counts` : counts of non-zero samples per observation, suggest 10 bins
- `observation_histogram_bins` : bin edges for the samples per observation histogram
- `sample_min_count` : min sample count
- `sample_max_count` : max sample count
- `sample_mean_count` : mean sample count
- `sample_median_count` : median sample count
- `sample_std_count` : standard deviation of count
- `observation_min_count` : min sample count
- `observation_max_count` : max sample count
- `observation_mean_count` : mean sample count
- `observation_median_count` : median sample count
- `observation_std_count` : standard deviation of count

For the sample and observation groups (e.g., `/sample`), the following dataset is proposed:
- `counts` : the counts per ID, in index order with `ids`

The above provides sufficient detail to summarize a table (e.g., the output of `summarize-table`) plus more, without the need to load the table into memory.

**Comment by josenavas** [comment]
:+1:

**Comment by gregcaporaso** [comment]
:+1:

**Comment by wasade** [comment]
I'm hesitant to put this into 2.1.4 as I think it is better suited for a minor release instead of micro, but it wouldn't be too difficult to do if you guys think otherwise

**Comment by wasade** [comment]
These are fast to recalculate so closing as unnecessary.
