### ISSUE TITLE
Replace all mktemp calls with mkstemp

### ISSUE THREAD

**Issue by adamrp** [biocore/biom-format#616]
The mktemp function was deprecated almost 12 years ago, and should not be used for the reasons mentioned [here](https://docs.python.org/2/library/tempfile.html#tempfile.mktemp).

The best convention to use is of the form:

```python
from os import close
from tempfile import mkstemp

file_descriptor, filepath = mkstemp()
close(file_descriptor)
with open(filepath, 'w') as new_file:
    # do stuff with new_file
```

**Comment by adamrp** [comment]
Actually, an even better way is with `tempfile.NamedTemporaryFile`:

```python
from tempfile import NamedTemporaryFile
with NamedTemporaryFile() as tempfile:
    # do stuff with tempfile
# when the context is exited, the tempfile is automatically deleted
# unless delete=False is passed to the NamedTemporaryFile constructor
```

**Comment by gregcaporaso** [comment]
+1 for using the ``tempfile`` module. I think that should be our standard.
