### ISSUE TITLE
Remove the word "table" from the options for --table-type

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/biom-format#624]
Is it possible to delete the word "table" from the --table-type options? It seems redundant and not very clean. So the options would be (lowercase): metabolite, gene, otu, pathway, function, ortholog, taxon.

--table-type=TABLE_TYPE
                        the BIOM table type to get converted into. Required
                        when converting a classic table file to a BIOM table
                        file. Must be one of: metabolite table, gene table,
                        otu table, pathway table, function table, ortholog
                        table, taxon table [default: none]

**Comment by ElDeveloper** [comment]
I like this idea, though I worry about backwards compatibility. What are
others' thoughts.

**Comment by cuttlefishh** [comment]
I noticed that the first word is capitalized in some versions of BIOM.  So it's been changed once already (affecting backward compatibility).  This would be an additional change, but arguably one for the better.  Perhaps there's a way to allow for both the old and new versions, if this change were made?

**Comment by gregcaporaso** [comment]
You could also keep the current terms and make them aliases for the new
ones. I think it'd be nice from a UI perspective.

**Comment by cuttlefishh** [comment]
+1

**Comment by cuttlefishh** [comment]
Also, it might be worth adding a sentence saying what the --table-type attribute does. From my understanding, it is a piece of file metadata, but does not change how the values are stored.  Is that correct?

**Comment by wasade** [comment]
If there's continued interest here, @cuttlefishh, would you be able to issue a PR for aliases? Otherwise, I'm inclined to close this

**Comment by iimog** [comment]
I'd like to add, that `biom convert` allows an additional value for `--table-type` which is just `Table` (using the python `biom` tool version 2.1.5). This is also the default if no table-type is supplied. However the table-type `Table` is not part of the controlled vocabulary allowed for the `type` property in any of the specifications (1.0, 2.0, 2.1) on the [biom-format](http://biom-format.org) website. So strictly speaking the resulting biom files are not valid (in any of the versions 1.0, 2.0, 2.1).

If `Table` is indeed part of the controlled vocabulary it would be nice to add this to the documentation.

**Comment by wasade** [comment]
I'd welcome a PR on this, but given the limited interest this issue has received, I'm inclined to close for now.
