### ISSUE TITLE
Move CLI to click

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/biom-format#631]
It would be awesome if the CLI could be moved to click, are there any current technical limitations?

**Comment by wasade** [comment]
No, just dev effort and agree. I think there might already be an open issue?

**Comment by ElDeveloper** [comment]
Got it, couldn't find it, I only found mentions of click in the issues.

**Comment by wasade** [comment]
ah, well you take the :cake: :)

**Comment by josenavas** [comment]
If we move the CLI to click means that is a major release? Just checking cause I think I won't be backwards compatible, or am I missing something?

**Comment by wasade** [comment]
yes

**Comment by ElDeveloper** [comment]
3.0, here we go!

**Comment by wasade** [comment]
we could do a minor release i suppose

**Comment by gregcaporaso** [comment]
Just remember that backward compatibility is needed for ``biom-format >= 2.1.3, < 2.2.0`` - that's what QIIME depends on.

**Comment by wasade** [comment]
Ya, so I was thinking 2.2 instead of 3.0

**Comment by gregcaporaso** [comment]
Ok, perfect.

**Comment by ebolyen** [comment]
- [ ]   `add-metadata`        Add metadata to a BIOM table
- [ ]   `convert`             Convert to/from the BIOM table format
- [ ]   `normalize-table`     Normalize a BIOM table
- [ ]   `show-install-info`   Provide information about the biom-format installation
- [ ]   `subset-table`        Subset a BIOM table
- [ ]   `summarize-table`     Summarize sample or observation data in a BIOM table
- [ ]   `validate-table`      Validate a BIOM-formatted file

**Comment by gregcaporaso** [comment]
I've tested all of the commands presented on the website, and they're working as they did in 2.1.4. Closing this.

**Comment by ElDeveloper** [comment]
:fireworks:
