### ISSUE TITLE
Convert biom to classic table with sample metadata

### ISSUE THREAD

**Issue by weebeige** [biocore/biom-format#632]
I have a biom file that has sample metadata and OTU taxonomy data. When converting the biom file into a classic table, I loose the sample metadata. Is there a way to keep it i.e. to get a classic table with taxonomy and sample metadata?
Thanks

**Comment by gregcaporaso** [comment]
There's not unfortunately, sample metadata isn't supported in classic-formatted files (which was one of the reasons for the transition to BIOM).
