### ISSUE TITLE
Biom-format install issues on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by braukmann** [biocore/biom-format#636]
Hello,

I recently tried installing qiime using pip and received the following error during the installation of biom-format:

 building 'biom._filter' extension
    creating build/temp.macosx-10.10-x86_64-2.7
    creating build/temp.macosx-10.10-x86_64-2.7/biom
    clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/lib/python2.7/site-packages/numpy/core/include/numpy -I/usr/local/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c biom/_filter.c -o build/temp.macosx-10.10-x86_64-2.7/biom/_filter.o
    biom/_filter.c:258:10: fatal error: 'numpy/arrayobject.h' file not found
    #include "numpy/arrayobject.h"
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/dd/ymw96sls33lc2pzwtyw3hcn80000gp/T/pip-build-47v6GV/biom-format/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/dd/ymw96sls33lc2pzwtyw3hcn80000gp/T/pip-428KcK-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/dd/ymw96sls33lc2pzwtyw3hcn80000gp/T/pip-build-47v6GV/biom-format

I tried adding the location of the numpy headers using ln and it still cannot seems to locate array object.h.

Thank you,

Thomas

**Comment by wasade** [comment]
Hi Thomas,

Can you send the exact command you ran please?

**Comment by braukmann** [comment]
I first used  **pip install qiime** and then tried installing biom-format from source with **sudo python setup.py install**.

Thanks,

Thomas

**Comment by wasade** [comment]
`pip install qiime` will install biom. If it didn't, then that install failed. Can you please run `print_qiime_config.py -t`? 

Just a note, `sudo python setup.py install` is very different than `python setup.py install`, and that will cause confusion with libraries as you're installing into a different environment

**Comment by braukmann** [comment]
The output for print_qiime_config.py -t is:

Traceback (most recent call last):
  File "/usr/local/bin/print_qiime_config.py", line 57, in <module>
    raise ImportError("%s\n%s" % (e, core_dependency_missing_msg))
ImportError: No module named biom.util
See the QIIME Installation Guide: http://qiime.org/install/install.html

I did try but python setup.py install but I have a permission denied error for _filter.o.

Thank you,

Thomas

**Comment by wasade** [comment]
The permission denied error is due to the previous use of sudo.

Did you get any errors when you ran `pip install qiime`?

**Comment by braukmann** [comment]
The only error I received was for biom-format. Specifically **biom/_filter.c:258:10: fatal error: 'numpy/arrayobject.h' file not found**

**Comment by wasade** [comment]
This issue is likely more appropriate for the QIIME tracker then as the install for QIIME failed. That being said, can you send the output of the following please?

```bash
python -c "import numpy; print numpy.__version__"
```

**Comment by wasade** [comment]
...actually, any reason that you didn't do `pip install biom-format`?

**Comment by braukmann** [comment]
My output is: **1.9.2**

**Comment by braukmann** [comment]
I was wanting to try qiime.  The pip install bio-format gives the same error

**Comment by wasade** [comment]
Okay. I do recommend either the QIIME tracker or qiime-forum. Since you're on OS X though, the recommendation you'll likely get will be to use [macqiime](http://www.wernerlab.org/software/macqiime). 

I was able to build biom against 1.9.2 though on RHEL 6 from pip. 

Did you run any other commands using sudo? This issue smells like your environment just being out of sync.

```bash
(biomtesting)14:02:21 (mcdonadt@pando-3):~$ python -c "import biom; print biom.__version__"
2.1.4
(biomtesting)14:02:33 (mcdonadt@pando-3):~$ python -c "import numpy; print numpy.__version__"
1.9.2
```

**Comment by braukmann** [comment]
I try to avoid running sudo and generally use pip or home-brew to install packages.   I only used sudo in this instance because it was recommended by the install instructions on http://biom-format.org.  I will try installing via macqiime.

Thank you

**Comment by braukmann** [comment]
I just installed macqiime successfully.

Thanks for the help,

Thomas

**Comment by wasade** [comment]
Ugh. Thanks, that should be fixed. The req method is first using pip, will
update those docs on sudo.

**Comment by Jorge-C** [comment]
Hmmm we should probably update the instructions there to use pip instead of sudo!

**Comment by wasade** [comment]
Glad it worked! Sorry for the difficulty!

**Comment by braukmann** [comment]
No worries! It seems not to be able to find that header in OsX 10.10 using pip or installing from source.  I initially tried pip as instructed and then tried building form source (using sudo) but the mac-qiime solution works. 

Thank you again for all the help!

**Comment by braukmann** [comment]
Just an FYI, I managed to install biom-format using pip on MAC OSx 10.10.3 after installing Anaconda python for 2.7 (https://store.continuum.io/cshop/anaconda/) and it is still free.

Thomas
