### ISSUE TITLE
Issue with biom convert?

### ISSUE THREAD

**Issue by jtremblay** [biocore/biom-format#637]
Dear Biom-format developers,
When I try to convert a tsv biom table to hdf5 format with this command:

`biom convert -i ./otu_table.tsv -o ./otu_table.biom --table-type 'OTU table' --to-hdf5`

I get the following error
```
  File "/path/to/software/qiime/qiime-1.9.0/lib/python/biom/table.py", line 278, in vlen_list_of_str_formatter
    data[i, :len(value)] = value
TypeError: len() of unsized object
```

As a temporary fix, in table.py (line 272), I changed:
`value = np.asarray(m[header]) `
to
`value = str(value).split(";")`
Seems to do the job for now. My Lineages (taxonomy columns) were following this nomenclature:
`k__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Alteromonadales; f__Alteromonadaceae; g__AlteromonadaceaeFA`
Cheers,

**Comment by ElDeveloper** [comment]
Thanks for reporting this @jtremblay! @wasade do you happen to have any ideas?

**Comment by jtremblay** [comment]
np, however I just find out that when I convert back hdf5 tables to tsv, taxonomy lineages are not written - the taxonomy column (header included) is simply not there...

**Comment by wasade** [comment]
iirc, you need to explicitly indicate you want to retain a given
observation metadata when going to tsv. Have you looked at the examples in
`biom convert --help`?

**Comment by jtremblay** [comment]
My bad, when including appropriate options it works fine. Sorry.

**Comment by wasade** [comment]
No worries, glad to help! If things are working, could you close the issue
please?

**Comment by jtremblay** [comment]
Absolutely, done.

**Comment by wasade** [comment]
Thanks!
