### ISSUE TITLE
create "biom head" command to show the first n cols and rows of the table

### ISSUE THREAD

**Issue by josenavas** [biocore/biom-format#639]
Sometimes you don't know what is on the table, so seeing the first rows/cols in the summarize-table output can really useful.

**Comment by antgonza** [comment]
I suggest adding another parameter not changing the current summarize-table option.

**Comment by josenavas** [comment]
Make sure that the rows and columns that are shown actually include some data, if we choose the first X and Y it might not have any data, only 0.

**Comment by gregcaporaso** [comment]
It might make sense to build this into the ``__repr__`` method for the class (which would then be related to https://github.com/biocore/scikit-bio/issues/656).

**Comment by gregcaporaso** [comment]
This could look something like this:

```
import numpy as np

def tsv_repr(t, n):
    obs_ids = t.ids(axis='observation')[:n]
    sam_ids = t.ids(axis='sample')[:n]
    data = np.zeros((n,n))
    for i, sam_id in enumerate(sam_ids):
        for j, obs_id in enumerate(obs_ids):
            data[i,j] = t.get_value_by_ids(obs_id, sam_id)
    print('\t' + '\t'.join(sam_ids))
    for obs_id, datum in zip(obs_ids, data):
        print('\t'.join([obs_id] + map(str,list(datum))))
            
tsv_repr(t, 5)
```

<img width="759" alt="screenshot 2015-10-14 13 57 24" src="https://cloud.githubusercontent.com/assets/192372/10497593/893786ca-727b-11e5-93ac-748a5a0e64d5.png">

(but formatted nicer).

**Comment by gregcaporaso** [comment]
... or maybe this would make more sense as a new ``biom head`` command?

**Comment by wasade** [comment]
I like head as its not a "summarization"

**Comment by gregcaporaso** [comment]
added in #669
