### ISSUE TITLE
Biom-format install issue on Mac OS X 10.8.5 (Cannot locate working compiler)

### ISSUE THREAD

**Issue by roserise** [biocore/biom-format#641]
I have a problem in installing Biom-format.
- mY mac is Mac OS X 10.8.5
- Python 2.7.10
- I have installed numpy  through: pip install bumpy
  and got: Successfully installed numpy-1.9.2
  then confirmed: python -c "import numpy; print numpy.**version**"
  1.9.2
- then i have a problem in installing biom-format through: pip install biom-format
  Collecting biom-format
  Downloading biom-format-2.1.4.tar.gz (435kB)
    100% |████████████████████████████████| 438kB 35kB/s 
  Requirement already satisfied (use --upgrade to upgrade): numpy>=1.3.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from biom-format)
  Collecting pyqi==0.3.2 (from biom-format)
  Downloading pyqi-0.3.2.tar.gz (240kB)
    100% |████████████████████████████████| 241kB 74kB/s 
  Collecting scipy>=0.13.0 (from biom-format)
  Downloading scipy-0.16.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (20.5MB)
  100% |████████████████████████████████| 20.5MB 11kB/s 
  Installing collected packages: pyqi, scipy, biom-format
  Running setup.py install for pyqi
  Running setup.py install for biom-format
    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;**file**='/private/var/folders/33/zygxjp6d4cjg88b_ny_pq7nc0000gn/T/pip-build-ZIQRUu/biom-format/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/33/zygxjp6d4cjg88b_ny_pq7nc0000gn/T/pip-eS1MWo-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-2.7
    creating build/lib.macosx-10.6-intel-2.7/biom
    copying biom/**init**.py -> build/lib.macosx-10.6-intel-2.7/biom
    copying biom/err.py -> build/lib.macosx-10.6-intel-2.7/biom
    copying biom/exception.py -> build/lib.macosx-10.6-intel-2.7/biom
    copying biom/parse.py -> build/lib.macosx-10.6-intel-2.7/biom
    copying biom/table.py -> build/lib.macosx-10.6-intel-2.7/biom
    copying biom/util.py -> build/lib.macosx-10.6-intel-2.7/biom
    creating build/lib.macosx-10.6-intel-2.7/biom/commands
    copying biom/commands/**init**.py -> build/lib.macosx-10.6-intel-2.7/biom/commands
    copying biom/commands/installation_informer.py -> build/lib.macosx-10.6-intel-2.7/biom/commands
    copying biom/commands/metadata_adder.py -> build/lib.macosx-10.6-intel-2.7/biom/commands
    copying biom/commands/table_converter.py -> build/lib.macosx-10.6-intel-2.7/biom/commands
    copying biom/commands/table_normalizer.py -> build/lib.macosx-10.6-intel-2.7/biom/commands
    copying biom/commands/table_subsetter.py -> build/lib.macosx-10.6-intel-2.7/biom/commands
    copying biom/commands/table_summarizer.py -> build/lib.macosx-10.6-intel-2.7/biom/commands
    copying biom/commands/table_validator.py -> build/lib.macosx-10.6-intel-2.7/biom/commands
    creating build/lib.macosx-10.6-intel-2.7/biom/interfaces
    copying biom/interfaces/**init**.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces
    creating build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse
    copying biom/interfaces/optparse/**init**.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse
    copying biom/interfaces/optparse/input_handler.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse
    copying biom/interfaces/optparse/output_handler.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse
    creating build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse/config
    copying biom/interfaces/optparse/config/**init**.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse/config
    copying biom/interfaces/optparse/config/add_metadata.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse/config
    copying biom/interfaces/optparse/config/convert.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse/config
    copying biom/interfaces/optparse/config/normalize_table.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse/config
    copying biom/interfaces/optparse/config/show_install_info.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse/config
    copying biom/interfaces/optparse/config/subset_table.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse/config
    copying biom/interfaces/optparse/config/summarize_table.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse/config
    copying biom/interfaces/optparse/config/validate_table.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/optparse/config
    creating build/lib.macosx-10.6-intel-2.7/biom/interfaces/html
    copying biom/interfaces/html/**init**.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html
    copying biom/interfaces/html/input_handler.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html
    copying biom/interfaces/html/output_handler.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html
    creating build/lib.macosx-10.6-intel-2.7/biom/interfaces/html/config
    copying biom/interfaces/html/config/**init**.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html/config
    copying biom/interfaces/html/config/add_metadata.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html/config
    copying biom/interfaces/html/config/convert.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html/config
    copying biom/interfaces/html/config/normalize_table.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html/config
    copying biom/interfaces/html/config/show_install_info.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html/config
    copying biom/interfaces/html/config/summarize_table.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html/config
    copying biom/interfaces/html/config/validate_table.py -> build/lib.macosx-10.6-intel-2.7/biom/interfaces/html/config
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/33/zygxjp6d4cjg88b_ny_pq7nc0000gn/T/pip-build-ZIQRUu/biom-format/setup.py", line 111, in <module>
        classifiers=classifiers
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 50, in run
        _build_ext.run(self)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 307, in run
        customize_compiler(self.compiler)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/sysconfig.py", line 171, in customize_compiler
        _osx_support.customize_compiler(_config_vars)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_osx_support.py", line 418, in customize_compiler
        _find_appropriate_compiler(_config_vars)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_osx_support.py", line 191, in _find_appropriate_compiler
        "Cannot locate working compiler")
    SystemError: Cannot locate working compiler
  ---
  
    Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;**file**='/private/var/folders/33/zygxjp6d4cjg88b_ny_pq7nc0000gn/T/pip-build-ZIQRUu/biom-format/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/33/zygxjp6d4cjg88b_ny_pq7nc0000gn/T/pip-eS1MWo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/33/zygxjp6d4cjg88b_ny_pq7nc0000gn/T/pip-build-ZIQRUu/biom-format
- How could i fix this problem???

**Comment by wasade** [comment]
It looks like you don't have [Xcode](https://developer.apple.com/xcode/downloads/) installed? Xcode is the developer stack from Apple and it contains the necessary toolchains to compile C programs (among other languages)

**Comment by roserise** [comment]
Thanks a lot for your rapid reply.
I found 2 versions of Xcode:
- Xcode 7 beta 6
- Xcode 6.4
Which one is suitable?

**Comment by wasade** [comment]
6.4? No need for beta

**Comment by wasade** [comment]
I'm closing this issue as I believe it was an environment problem. Please reopen if necessary.
