### ISSUE TITLE
method to convert biom counts to ranked abundances

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/biom-format#645]
I'm working on an analysis where I'd like to identify the most abundant through least abundant observations on a per-sample basis. Is this something that others would like to see in BIOM? For example:

<img width="643" alt="screenshot 2015-10-14 06 34 19" src="https://cloud.githubusercontent.com/assets/192372/10485187/b08fd396-723d-11e5-897a-44e12a0ab3dc.png">

cc @wasade

If so, should it be it's own method, or would it fit better in an existing method? (Or better yet, is it currently possible and I just don't know about it?)

**Comment by wasade** [comment]
:+1:

**Comment by antgonza** [comment]
I like it but what about sorting vs. changing the values, I could see some user getting confused and using the resulting biom for other analysis?

**Comment by gregcaporaso** [comment]
I need the values changed for the analysis that I want to do (and there is no way to achieve a similar result with sorting anyway as the ranking is on a per-sample basis). We can't really protect users against mis-using their files. 

@wasade, what do you think - part of an existing method, or a new method?

**Comment by antgonza** [comment]
OK, thanks for the explanation.

**Comment by wasade** [comment]
I believe this can be expressed as a transform (but may be wrong about
that). I think it's generality suggests it should be an exposed api method
that makes a call to the transform method. Does that make sense?

**Comment by gregcaporaso** [comment]
Yep, that makes sense. Thanks!
