### ISSUE TITLE
Have Travis enumerate supported Py3 versions

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#646]
Need to respect Cython. Open question: docs in py2 or py3? The specific py3 versions to support are not defined yet.

**Comment by gregcaporaso** [comment]
I vote not changing the docs to Py3 at this moment so it doesn't hold us up (unless we have time before we cut a release), though ideally I think Py3 docs is where we'd want to go. 

How about official support for Py 2.7 and 3.5 (so that's what we test with)?

**Comment by ebolyen** [comment]
fixed in #661
