### ISSUE TITLE
support generation of biom files from uc/bl9?

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/biom-format#648]
I've been working on some code to get vsearch-dereplicated reads into a BIOM file ([doc](https://github.com/gregcaporaso/scaling-octo-robot#vsearch-dereplication-to-biom-and-representative-sequences)), and have a small test repo [here](https://github.com/gregcaporaso/scaling-octo-robot). Would it be worth hooking these functions up to the command line for the 2.1.5 release, so we make this accessible to our users? I plan to use that code regardless, so really it's just a question of whether it should go in biom, or stay stand-alone (in which case I'll be adding tests to that repo, cleaning it up, and making it pip/conda installable.

**Comment by wasade** [comment]
:+1:

**Comment by ebolyen** [comment]
fixed in #675
