### ISSUE TITLE
use locale for nicer formatting of numbers in biom summarize-table output

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/biom-format#679]
Use ``locale.format(<number>, grouping=True)`` to insert commas in big numbers to make them more readable. For example:

```
Num samples: 986
Num observations: 3936860
Total count: 32822192
Table density (fraction of non-zero values): 0.002
```

would become:

```
Num samples: 986
Num observations: 3,936,860
Total count: 32,822,192
Table density (fraction of non-zero values): 0.002
```

**Comment by wasade** [comment]
:+1:

**Comment by ElDeveloper** [comment]
:+1:

**Comment by gregcaporaso** [comment]
Ah, much better:

![screenshot 2015-11-10 10 14 30](https://cloud.githubusercontent.com/assets/192372/11069594/15c961a8-8794-11e5-9998-d96e5b5c325f.png)

**Comment by wasade** [comment]
It may be nice for this to be optional, although there are a few other things that would be nice to have in `summarize-table`, like just dumping out `axis_id <TAB> count`. I can see having just the big picture summary as in, everything above "Counts/sample detail" as nice to have optionally, but this is beginning to get distinct from this issue
