### ISSUE TITLE
biom from-uc arguments

### ISSUE THREAD

**Issue by gblanchard4** [biocore/biom-format#683]
Thanks for the recent addition of the `from-uc` option. When I first tried to use it without reading the great [writeup](https://gist.github.com/gregcaporaso/f3c042e5eb806349fa18) Greg Caporaso did, I ran into an issue that I think some users *might* have too. 

When I just run `biom from-uc` it lists:
```
biom from-uc  
Usage: biom from-uc [OPTIONS]

Error: Missing option "-i" / "--input-fp"
```
If I run it with just the `-i` option I then get: `AttributeError: 'NoneType' object has no attribute 'encode'`

I recognized this is due to not having the output specified, but other users may not.

I guess this comes down to the output not being required option. Can the script do anything without specifying output, or will it always give throw `AttributeError`?

**Comment by gregcaporaso** [comment]
Thanks for point this out. This is an oversight (``-o`` should be required) - I'll get it fixed for the next release.
