### ISSUE TITLE
bug/incorrect documentation for nonzero_counts binary variable

### ISSUE THREAD

**Issue by amnona** [biocore/biom-format#685]
in table.nonzero_counts(axis='sample',binary=False) it seems the output is the total number of reads per sample, whereas binary=True gives the number of nonzero OTUs.
this is opposite of the documentation.
Also, the default should be to get the number of nonzero OTUs (i.e. True in current case)

**Comment by wasade** [comment]
Resolution of this issue will be deferred until 2.2.0 as this necessitates an API change. I do not see a discrepancy in the documentation but I agree that `binary=False` is not ideal.
