### ISSUE TITLE
hackishly bump biom to 2.2.0

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/biom-format#687]
Could we, in the eternal words of @wasade, 'hackishly bump biom to 2.2.0'?

This minor release will mark our transition to qiime 2 and allow us to move away from the qiime 1.x codebase and extraneous dependencies. This will also elegantly address biocore/conda-recipes/pull/45.

**Comment by wasade** [comment]
@colinbrislawn, is this still necessary? I'm closing out as I don't think it is, but please reopen if necessary.

**Comment by colinbrislawn** [comment]
Nope. This was suggested as a workaround to make a conda package for `biom-format``. @bgruening made [a biom-format package on bioconda](https://bioconda.github.io/recipes/biom-format/README.html), so we can safely close this.
