### ISSUE TITLE
test data not included in pip package

### ISSUE THREAD

**Issue by wwood** [biocore/biom-format#693]
Hi,

I'm trying to run `python setup.py test` but am running into errors which I believe are caused by test data not being distributed. If I'm correct, would it be possible to add them in please?

```
======================================================================
ERROR: test_subset_observations_hdf5 (tests.test_cli.test_subset_table.TestSubsetTable)
Correctly subsets samples in a hdf5 table
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/n6qh8hnxw0iyhlmacbq1w9800qgaxcgy-python2-numpy-1.10.4/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/tmp/guix-build-python2-biom-format-2.1.5.drv-0/biom-format-2.1.5/tests/test_cli/test_subset_table.py", line 82, in test_subset_observations_hdf5
    json_table_str=None)
  File "/tmp/guix-build-python2-biom-format-2.1.5.drv-0/biom-format-2.1.5/biom/cli/table_subsetter.py", line 135, in _subset_table
    with biom_open(hdf5_biom) as f:
  File "/gnu/store/kcc3cxnx9l2hbg7pjhxsa0r5yq2j2f38-python-2.7.10/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/tmp/guix-build-python2-biom-format-2.1.5.drv-0/biom-format-2.1.5/biom/util.py", line 440, in biom_open
    if os.path.getsize(fp) == 0:
  File "/gnu/store/kcc3cxnx9l2hbg7pjhxsa0r5yq2j2f38-python-2.7.10/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: 'test_data/test.biom'
```

Please excuse the strange paths, I am attempting to package bio for guix.

Thanks.
ben

**Comment by wasade** [comment]
How did you install BIOM? I'm not able to replicate this when I run `python setup.py test`

**Comment by wwood** [comment]
I'm attempting to package biom for Guix
https://www.gnu.org/software/guix/

Happy to provide the further details if you like but is it suffice to say that `test_data/test.biom` (among others e.g. the .json test file) is not included in the pip distributed archive?
https://pypi.python.org/pypi/biom-format/2.1.5

**Comment by wasade** [comment]
Thanks! Confirmed, pypi package does not have the tests -- thanks. And thanks for packaging this for Guix!

Likely quick fix is to add `__init__.py` to `tests/test_data`

**Comment by wasade** [comment]
Should be solved by #733 with the inclusion of an `__init__.py` to the test data directory

**Comment by wwood** [comment]
Unfortunately this does not seem to have worked - as of 2.1.6 there is now a `test_data` directory with an `__init__.py` but there is no actual data in it.

FWIW we have incorporated biom into Guix now, we just grab the sources from GitHub rather than PyPI.

**Comment by wasade** [comment]
Hi @wwood, would you be able to issue a PR to correct the issue?

**Comment by ebolyen** [comment]
Just saw this on my feed and thought I would chime in,

It doesn't look like `biom` sets up `package_data` (but it does have a MANIFEST). My understanding is you need both. What kind of sucks is you'll need to specify *every* directory (recursive glob syntax doesn't work). 

[scikit-bio's setup.py](https://github.com/biocore/scikit-bio/blob/8cb97248c6fe5b84312a3e4f74c20bfb19cc8d0e/setup.py#L124-L132) is a good example of this.

**Comment by wasade** [comment]
Thanks, @ebolyen!
