### ISSUE TITLE
minor documentation issue with table.data

### ISSUE THREAD

**Issue by wdwvt1** [biocore/biom-format#694]
`table.data` takes an ID (for sample or observation). The documentation string says:

``` python
id : str
    ID of the samples or observations whose data will be returned.
```

This function does not accept any iterable of sample or observations - it will error indicating unhashable type. This parameter string suggests an iterable can be passed.

**Comment by wasade** [comment]
The docstring is accurate, but the plurals in "samples" and "observations" is misleading. Are you able to issue a quick PR on this by chance?
