### ISSUE TITLE
ImportError: Unable to load base config module: biom.interfaces.optparse.config

### ISSUE THREAD

**Issue by tallnuttphone** [biocore/biom-format#703]
Hi,

tearing my hair out trying to get biom to run, always get the error below. I am not admin of my machine, so can't easily make changes or find out how it was installed. Do you have any suggestions I could pass on or try myself? I have tried adding every biom library directory I could find to PYTHONPATH but made no difference.

Thanks,

S.

$biom
Traceback (most recent call last):
  File "/usr/local/bin/pyqi", line 148, in <module>
    command_names = get_command_names(cmd_cfg_mod)
  File "/usr/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/interface.py", line 276, in get_command_names
    config_base_name)
ImportError: Unable to load base config module: biom.interfaces.optparse.config

**Comment by wasade** [comment]
It looks like the system install is messed up, and it also looks like the system install is an out-of-date version of biom. Can you just install locally? If you're not familiar with it, I recommend using [Anaconda](https://www.continuum.io/downloads). It does not require administrative access, and biom can then be installed as easily as `conda install -c bioconda biom-format`

**Comment by wasade** [comment]
@tallnuttphone, I just saw that you opened an issue on the QIIME forum as well. I'm going to close this issue out, and respond there as it is a wider audience. I do not see any evidence of a bug in biom, it most likely is the system environment out of sync. System-wide installs libraries like this is generally a bad idea as it is easy for there to be version mismatches in dependencies.
