### ISSUE TITLE
Unable to install v 2.1.5 on OSX 10.11.2

### ISSUE THREAD

**Issue by amalacrino** [biocore/biom-format#705]
Hello, since I want to use `from-uc` I tried to install the last version, however when I try with

`sudo pip install biom-format`

I get
`Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Ik0tHF/biom-format/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Pt8mPM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Ik0tHF/biom-format/`

How can I solve it?
Thanks!

P.S.: This is the complete message:

Collecting biom-format
  Downloading biom-format-2.1.5.tar.gz (307kB)
    100% |████████████████████████████████| 317kB 2.7MB/s 
Requirement already satisfied (use --upgrade to upgrade): click in /usr/local/lib/python2.7/site-packages (from biom-format)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.3.0 in /usr/local/lib/python2.7/site-packages (from biom-format)
Requirement already satisfied (use --upgrade to upgrade): future>=0.14.3 in /usr/local/lib/python2.7/site-packages (from biom-format)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.13.0 in /usr/local/lib/python2.7/site-packages (from biom-format)
Requirement already satisfied (use --upgrade to upgrade): pyqi in /usr/local/lib/python2.7/site-packages (from biom-format)
Installing collected packages: biom-format
  Running setup.py install for biom-format ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Ik0tHF/biom-format/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Pt8mPM-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-2.7
    creating build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/err.py -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/exception.py -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/parse.py -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/table.py -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/util.py -> build/lib.macosx-10.11-x86_64-2.7/biom
    creating build/lib.macosx-10.11-x86_64-2.7/tests
    copying tests/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/tests
    copying tests/test_err.py -> build/lib.macosx-10.11-x86_64-2.7/tests
    copying tests/test_parse.py -> build/lib.macosx-10.11-x86_64-2.7/tests
    copying tests/test_table.py -> build/lib.macosx-10.11-x86_64-2.7/tests
    copying tests/test_util.py -> build/lib.macosx-10.11-x86_64-2.7/tests
    creating build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/installation_informer.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/metadata_adder.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/table_converter.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/table_head.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/table_normalizer.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/table_subsetter.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/table_summarizer.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/table_validator.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/uc_processor.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    copying biom/cli/util.py -> build/lib.macosx-10.11-x86_64-2.7/biom/cli
    creating build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    copying tests/test_cli/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    copying tests/test_cli/test_add_metadata.py -> build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    copying tests/test_cli/test_show_install_info.py -> build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    copying tests/test_cli/test_subset_table.py -> build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    copying tests/test_cli/test_summarize_table.py -> build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    copying tests/test_cli/test_table_converter.py -> build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    copying tests/test_cli/test_table_normalizer.py -> build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    copying tests/test_cli/test_uc_processor.py -> build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    copying tests/test_cli/test_validate_table.py -> build/lib.macosx-10.11-x86_64-2.7/tests/test_cli
    running egg_info
    writing requirements to biom_format.egg-info/requires.txt
    writing biom_format.egg-info/PKG-INFO
    writing top-level names to biom_format.egg-info/top_level.txt
    writing dependency_links to biom_format.egg-info/dependency_links.txt
    writing entry points to biom_format.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found
    reading manifest file 'biom_format.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '.git' found anywhere in distribution
    writing manifest file 'biom_format.egg-info/SOURCES.txt'
    copying biom/_filter.c -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/_filter.pyx -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/_subsample.c -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/_subsample.pyx -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/_transform.c -> build/lib.macosx-10.11-x86_64-2.7/biom
    copying biom/_transform.pyx -> build/lib.macosx-10.11-x86_64-2.7/biom
    running build_ext
    building 'biom._filter' extension
    creating build/temp.macosx-10.11-x86_64-2.7
    creating build/temp.macosx-10.11-x86_64-2.7/biom
    clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c biom/_filter.c -o build/temp.macosx-10.11-x86_64-2.7/biom/_filter.o
    biom/_filter.c:258:10: fatal error: 'numpy/arrayobject.h' file not found
    #include "numpy/arrayobject.h"
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Ik0tHF/biom-format/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Pt8mPM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Ik0tHF/biom-format/

**Comment by wasade** [comment]
@amalacrino, it looks like it isn't finding the numpy headers, which is odd. Are you able to install via conda? If not, what I recommend trying next is to `pip install numpy` first, and then install `biom`. pip is a little finicky with numpy.

On an aside, there isn't a need to use sudo.

**Comment by wasade** [comment]
Closing as unclear if there is still an issue. Please reopen if necessary

**Comment by gawbul** [comment]
Same issue for me too! Can't install biom-format 2.1.5 on macOS 10.12.1.

I'm seeing lots of people recommended using conda, and other work arounds, in various posts across git/stackoverflow, e.g.:

- http://stackoverflow.com/questions/36473298/error-with-pip-install-biom-format-numpy-arrayobject-h-file-not-found
- https://github.com/biocore/biom-format/issues/636
- https://github.com/biocore/biom-format/issues/702

No-one seems to be giving an actual fix for a vanilla pip install however? Though it it seems to be something macOS related, as install on my Ubuntu 16.10 machine worked fine.

Perhaps the commit from @epruesse above resolves things? I'll try have a play with that! Can that be merged if so?

**Comment by wasade** [comment]
I'd be happy to review and merge a PR if one is issued.

**Comment by gawbul** [comment]
@wasade, awesome, thanks! @epruesse's fix seems to resolve things for me. Hope he will submit a PR.

**Comment by epruesse** [comment]
@wasade: The PR was https://github.com/biocore/biom-format/pull/713 -- you merged it minutes after the commit on 10/7. All that's needed is a 2.1.6 release. ;-)

@gawbul: pip can install directly from github, including references to specific commits. So until a 2.1.6 is out, you could install  biom-format in the state it was right after the merge of my patch like so:
```
pip install git+git://github.com/biocore/biom-format.git@efa20e1d3104aada0383b35dbe976de17717e61c
```

Or leave out the `@efa...` to just pull and install the most current state.

**Comment by wasade** [comment]
Ah :) thanks. That's why it seemed so familiar... I don't have an ETA yet on 2.1.6. The corresponding milestone lays out what I'd like to resolve before release though.

**Comment by nextgenusfs** [comment]
Not sure this thread should be closed until 2.1.6 is available - or perhaps this could be put on the boom-format page until 2.1.6 is released.  Took quite a bit of digging to find this.  Had the same problem with install on Mac OS Sierra. @epruesse command above fixed it.

**Comment by wasade** [comment]
@nextgenusfs would love some help knocking out issues for 2.1.6 :) Oddly, I'm on Sierra and have not had this problem.

**Comment by nextgenusfs** [comment]
I'd love to help, but don't know much about pip and how it works.  I can get more info off my system if that is helpful?

**Comment by wasade** [comment]
I believe this issue is resolved within `master` already, however there is a [list](https://github.com/biocore/biom-format/milestone/11) of issues which we'd like to resolve prior to cutting 2.1.6.

**Comment by gawbul** [comment]
@wasade I think it is something to do with having a non-standard Python install (I use pyenv) and installing libraries to `~/.local` or some other location instead of `/Library/...`?

**Comment by nextgenusfs** [comment]
That would potentially make sense with my setup, I'm running python 2.7.12 installed via home-brew.  I think the same is true of home-brew install, goes somewhere in the `/usr/local/Cellar`

**Comment by wasade** [comment]
I use conda and avoid sudo

**Comment by epruesse** [comment]
The "problem" is that Cython only looks for header files in the system paths by default. That works if you installed numpy "system wide", e.g. with a package manager or using system wide `pip`. But there are many other places where it might be, ranging from `/Applications/Xcode.app/...` over `/System/Library/Frameworks/PythonX.Y/...`, `/usr/local/Cellar/...` to `~/.local/...` or even `$(pwd)/.tox`. It's actually not unlikely to be in several places.

The (merged) patch uses numpy's own function to determine where the header files **matching** the loaded module are. Even if it works without that, it might just "happen to" and would break if the numpy versions installed differed at binary API level.

All I did was move the call setting the `include_dirs` to the right place. Unfortunately, `included_dirs` is one of the parameters `setup()` accepts and just stores. It doesn't seem to be used. For Cython, it has to be set via the `Extension` constructor for each extension. Otherwise, it's not really set. It's hard to notice, because "developer machines" will usually have a numpy in a system location. It's made worse by a confusing / wrong statement in the Cython docs, setting people on a path that doesn't have any effect at all -- biom-format isn't alone in having had this wrong.

**Comment by wasade** [comment]
I do not do systemwide installs, although I agree with the cython issue
noted and thanks again for the fix :). This could be an issue with brew
doing something unexpected -- I do not use it for Python.
