### ISSUE TITLE
error in importing biom file from QIIME to R using the biom package

### ISSUE THREAD

**Issue by mingjiew** [biocore/biom-format#711]
I am trying to use the 'biom' package to import a biom file generated by QIIME to R (3.2.3). 
> biom_file <- system.file("extdata", "out.biom", package = "biom")

> x = read_biom(biom_file)

Error in fromJSON(content, handler, default.size, depth, allowComments,  : 

  invalid JSON input

Do you know the reason for the error? I even used biom convert in QIIME to explicitly convert the biom file into JSON format and still it has the same error. I know the 'biomformat' package might be better, but for now I need to use R 3.2.3.

**Comment by wasade** [comment]
Closing as off topic, this repository does not maintain the R biom library. From looking at their github repo, however, it appears a parallel issue was already created there
