### ISSUE TITLE
MEGAN6 biom duplicate id error - way to generate random id from an existing biom table

### ISSUE THREAD

**Issue by FCMicrobes** [biocore/biom-format#714]
Hello,

I would like to analyse the "Functional table" from Megan6 with phyloseq R-package.
I am able to export the Kegg functional table in biom format from Megan6, but the id is the K0 and depending on the dataset some K0 are shared among different pathways and thus there are a duplicate id error. 
Is there any easy way to generate random id?

Thanks a lot.

Cheers

<img width="503" alt="screen shot 2016-10-10 at 8 54 24 pm" src="https://cloud.githubusercontent.com/assets/19280029/19237761/0b75b7b0-8f31-11e6-99a4-394536e18d2f.png">

<img width="633" alt="screen shot 2016-10-10 at 8 54 53 pm" src="https://cloud.githubusercontent.com/assets/19280029/19237768/1075197c-8f31-11e6-87f3-92d0fecce101.png">

**Comment by wasade** [comment]
As you've indicated, the table is not a validly formatted BIOM table, and as a result, the tools in this repository are not going to be able to parse it. I recommend contacting the developers of the software which produced the table.

Note: with PICRUSt, the strategy is to describe the different pathways a KO belongs too in the metadata.
