### ISSUE TITLE
`Table.__init__` should enforce float type

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#718]
...some methods, such as `Table.filter`, assume specific types and will error, and as such the constructor should normalize, error or warn. Alternatively, we revert BIOM to allow `int`.

**Comment by wasade** [comment]
Fixed in #733

**Comment by peterjc** [comment]
Quoting the change log for 2.1.6,

> ``Table.__init__`` now always performs an ``astype(float)`` on the contained spmatrix. This type normalization is beneficial for underlying Cython code on the filtering and transform operations. It is possible this will introduce some performance overhead, however in _most_ cases the data should already be float. See https://github.com/biocore/biom-format/issues/718.

Is the rational for not allowing ``int`` explained somewhere? Many (all?) of the examples in the documentation seem to use integer counts, so this surprised me.

**Comment by wasade** [comment]
@peterjc the format itself is `float64` for [data](https://github.com/biocore/biom-format/blob/master/doc/documentation/format_versions/biom-2.1.rst?plain=1#L42) and the example is also float64:

```python
In [12]: f = h5py.File('min_sparse_otu_table_hdf5.biom', 'r')

In [13]: f['sample/matrix/data'].dtype
Out[13]: dtype('<f8')
```

The DDL example is also [float64](https://github.com/biocore/biom-format/blob/master/doc/documentation/format_versions/biom-2.1.rst?plain=1#L170). 

Microbiome data are often represented in both count and relative abundance with the latter being real valued. Given that the data being operated on frequently are going be within a floating point space, we opted to simplify the type definition, and associated IO operations, to be data type specific.

**Comment by peterjc** [comment]
Thanks - that makes sense, although one might have argued for integer counts being common enough to justify explicitly being supported (more disk and memory efficient), I understand that complexity would have come at a cost.

**Comment by wasade** [comment]
That is an excellent point. But if we do push out a new format version, I think the bigger bang would be to limit storage to only CSR or CSC rather than duplication. And I _think_ we would still need to use `uint64` actually as IIRC the intensity values for MS data can be quite large
