### ISSUE TITLE
biom convert to json writes the type as a byte literal

### ISSUE THREAD

**Issue by corburn** [biocore/biom-format#731]
In python 3, biom convert will write the `type` as a byte literal. As a result, the `type` is not recognize by scripts expecting a string literal. This can be reproduced with the biom-format test data where, unlike the data this was encountered in, the `id` is also written as a byte literal:
```
biom convert -i  tests/test_data/test.biom -o test.json --to-json

{
  "id": "b'No Table ID'",
  "type": "b'Unspecified'"
  ...
}
```

Including the table-type flag will replace the byte literal with a string literal.
`biom convert -i  tests/test_data/test.biom -o test.json --to-json --table-type "OTU table"`

System information
==================
         Platform:	linux
   Python version:	3.4.2 (default, Oct  8 2014, 10:45:20)  [GCC 4.9.1]
Python executable:	/biom-format/env/bin/python3

Dependency versions
===================
click version:	6.7
NumPy version:	1.12.0
SciPy version:	0.18.1
 h5py version:	2.6.0

biom-format package information
===============================
biom-format version:	2.1.5-dev

**Comment by wasade** [comment]
Good catch. Am surprised this hasn't popped up or was caught by the test
harness. Will investigate today, thank you for creating the issue!
