### ISSUE TITLE
Not working under Windows

### ISSUE THREAD

**Issue by ZeweiSong** [biocore/biom-format#736]
I posted this question at BioStars:

I tried to install Biom format from the source under Windows:
@python setup.py install
However, when I typed the following to check the version, I got a error message:
@python -c "from biom import __version__; print __version__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "biom\__init__.py", line 65, in <module>
    from .table import Table
  File "biom\table.py", line 194, in <module>
    from ._filter import _filter
ImportError: No module named _filter
Any idea on how can I make it work in Windows?

**Comment by wasade** [comment]
Hi @ZeweiSong, what I suspect is that the Cython code needs to be regenerated. To do so, you need to make sure Cython is in the environment (e.g., `pip install cython`). You should then be able to ask biom to regenerate the extensions with `python setup.py build_ext`, and then a install _might_ work. None of the developers use Windows machines though, so this is an untested platform for us at this time.

**Comment by auberginekenobi** [comment]
I get the same error using build_ext as build - it doesn't look like that install solution works.

**Comment by wasade** [comment]
@auberginekenobi it's unfortunate but I'm not very surprised. I don't believe any of the contributors to this project have Windows machines for development use which has presented challenges testing on that platform.

**Comment by auberginekenobi** [comment]
Potential workarounds for Windows users who visit this page in the future:
- biom-format installs successfully on the Ubuntu shell that comes with the latest update of Windows 10
- use a virtual machine, such as QIIME - already comes with biom-format installed
- biom-format installs successfully on Windows distributions of R (even the python commands work...)

**Comment by wasade** [comment]
That's useful, thank you for adding those comments and observations!

**Comment by wasade** [comment]
Closing as it doesn't seem like there is a strong push to support Windows.

**Comment by ElDeveloper** [comment]
:neckbeard: ... actually, it looks like the windows build works. See the [conda-forge feedstock here](https://github.com/conda-forge/biom-format-feedstock), notice how the Windows build is "passing". It would be good if someone could try this and report back. `conda install -c conda-forge biom-format`.

**Comment by wasade** [comment]
Oh, accidental support?
