### ISSUE TITLE
Feature request: add explicit support for NA values

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/biom-format#755]
Depending on the software and statistics applied, NA values inside a feature-abundance table could indicate an error, or could be equivalent to zero, or **could indicate that no value is present**.

Is that last case, in which values are intentionally left blank, currently supported in the biom format?

Do we want to support something like this?

The R language supports `NA` and `NaN` and `null`, all with distinct meanings. Do we want to support something like this in qiime?

EDIT: some links
A qiime user [finds NaN in their data](https://groups.google.com/forum/#!topic/qiime-forum/EVTq3uRnuDI) (NaN is the the result of x/0)
A discussion of [how R handles missing data](https://www.oreilly.com/learning/handling-missing-data)

**Comment by wasade** [comment]
We rely on `scipy.sparse`, and until different zero values are supported, we're unable to support this.
