### ISSUE TITLE
`from_uc` command incorrectly handles sample ids with underscores

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/biom-format#758]
Sample ids containing underscores get truncated when creating a `biom.Table` object from a `.uc` file.

**Comment by wasade** [comment]
@gregcaporaso, do you still want to do this or should this be closed?

**Comment by gregcaporaso** [comment]
I still think this is worth addressing. I'll put this on my list - do you have a target date for a next release that I should shoot for?

**Comment by wasade** [comment]
Okay, thanks! Was hoping to release this week, is that feasible given your
schedule?
