### ISSUE TITLE
The to frame method is very slow because of pandas sparse representation

### ISSUE THREAD

**Issue by johnchase** [biocore/biom-format#762]
The `table.to_frame` method is very slow due to issues with pandas sparse representations 
Take for example the following table which is not too dissimilar to 16S data:

```python
data = np.random.randint(0, 2, (200, 3000))
```

Converting this to a `pd.SparseDataFrame`

```
%%timeit
df = pd.SparseDataFrame(data)
21.9 s ± 18.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Versus the dense representation:

```python 
%%timeit
df = pd.DataFrame(data)
107 µs ± 280 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

It makes one wonder how long a table that *had* to be stored in the sparse representation would actually take. Perhaps the time doesn't scale linearly for the sparse representation, though I would rather not wait around to find out .

I think at the very least the `to_frame` method could take a `representation` parameter that would allow the user to specify sparse of dense

**Comment by wasade** [comment]
Agree with the proposed representation parameter in hopes sparse with
pandas improves in the future. Thanks for the bug report!
