### ISSUE TITLE
Cannot install in R?

### ISSUE THREAD

**Issue by ZeweiSong** [biocore/biom-format#764]
I just try the install command in R and got this error message:

> install.packages("biom")
Installing package into ‘C:/Users/songz/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘biom’ is not available (for R version 3.4.2)

Any idea? Thanks!

Zewei

**Comment by smdabdoub** [comment]
See issue #152. The current R library is maintained by @joey711:

https://github.com/joey711/biomformat

**Comment by wasade** [comment]
Thanks, @smdabdoub!

@ZeweiSong, I'm closing this issue as it is not relevant for this repository.
