### ISSUE TITLE
read a biom file created by biomformat from qiime2

### ISSUE THREAD

**Issue by mostafaBio** [biocore/biom-format#766]
Hi All,
Greetings! I am using R. I have a biom file("file_1.biom):
1 I used the biomformat to read file_1.biom 
2-I did some editing on the data 
3- I wrote the biom file after editing using write_biom fiunction as "file_2.biom"
4- I can not use qiime2 to read the new biom file "file_2.biom"( I have the message Bad Request)
5- The point is I can read the original biom file using qiime2 but if read the original file using biomformat and just rewriting the original file again using write_biom I am not able to use qiime2 to read the new file.
Kind Regards.

**Comment by wasade** [comment]
Hi @mostafaBio, the R biomformat [package](https://github.com/joey711/biomformat) is not part of this repository. Can you reopen this issue with that project?
