### ISSUE TITLE
Table.remove_empty(inplace=False) is not honored

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#768]
...the kwarg is not passed onto the subsequent `Table.filter` [call](https://github.com/biocore/biom-format/blob/master/biom/table.py#L3158).

**Comment by antgonza** [comment]
This is potentially bad, right?

**Comment by wasade** [comment]
Very unlikely as this was introduced in 2.1.6, has limited adoption from what I've seen, and in general it's use is coupled to a `Table.filter(..., inplace=...)`

**Comment by antgonza** [comment]
Ohh makes sense, thanks!

**Comment by wasade** [comment]
Non-issue, the `table` is copied prior to `filter`.
