### ISSUE TITLE
Request : iloc functionality

### ISSUE THREAD

**Issue by mortonjt** [biocore/biom-format#775]
It would be really awesome if there were some functionality similar to the `iloc` functionality in pandas.

One use-case popping up is trying to grab `k` random samples from the biom table and keeping those samples in a sparse format.  Right now, the partition function isn't quite fitting the bill (although it is really close!).

**Comment by mortonjt** [comment]
Not quite - since subsample is doing rarefaction right?

**Comment by wasade** [comment]
`Table.subsample(..., by_id=True)` is how to do this

**Comment by mortonjt** [comment]
Whoa.  I guess I didn't read the documentation very carefully.  Thanks @ElDeveloper and @wasade !

Looking at the functionality, it looks like only subsampling without replacement is enabled.  For example if I run the command with the existing table
```
In [6]: table
Out[6]: 10 x 5 <class 'biom.table.Table'> with 20 nonzero entries (40% dense)

In [7]: table.subsample(10, axis='sample')
Out[7]: 6 x 3 <class 'biom.table.Table'> with 11 nonzero entries (61% dense)

In [8]: table.subsample(5, axis='sample')
Out[8]: 7 x 4 <class 'biom.table.Table'> with 13 nonzero entries (46% dense)
```

The subsample command won't actually return a full `n` entries.  This doesn't seem like a warranted feature.

This also seems relevant to #774 - I'll be happy to get started on this (since I need this pretty urgently anyways).

**Comment by wasade** [comment]
Great, thanks!
