### ISSUE TITLE
Clarify docstring for parse_biom_table?

### ISSUE THREAD

**Issue by AmandaBirmingham** [biocore/biom-format#776]
The parse_biom_table function in biom-format/biom/parse.py takes a parameter named "fp".  The docstring says in one place that this is a file path (as the name implies) but in another says it is a file-like object:

https://github.com/biocore/biom-format/blob/fa72347cdb2311610df8c390b976d936c6ae4270/biom/parse.py#L343-L349

From the way the method is used, it appears that the "file-like object" description is the correct one:

https://github.com/biocore/biom-format/blob/fa72347cdb2311610df8c390b976d936c6ae4270/biom/parse.py#L652-L654

If this is the case, I think it would be helpful to rename the parameter to something other than `fp` (`f`, maybe?) and change the docstring so it does not explicitly describe this as a file path.  (Similarly, changing the above code `biom_open(f) as fp` so that it does not use `fp` as a variable name for a file object might be less confusing :)  

Happy to submit  a teeny PR for this if developers agree it makes sense.

**Comment by ElDeveloper** [comment]
Fixed in #812
