### ISSUE TITLE
Test suite throws errors with latest dependencies (most probably numpy)

### ISSUE THREAD

**Issue by tillea** [biocore/biom-format#777]
Hi,
since a few days the test suite of the Debian packaged biom-format fails.  From the point in time this is quite closely connected to an update to numpy (currently 1.14.3 as well as 1.14.4).  Here is some extract of the log:

    $ python2.7 -m nose tests
    ...
    unzip(items) should be the inverse of zip(*items) ... ok

    ======================================================================
    FAIL: TableSummarizer functions as expected
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/tmp.ovLIvfIx3j/tests/test_cli/test_summarize_table.py", line 33, in test_default
        self.assertEqual(sorted(result), sorted(summary_default))
    AssertionError: Lists differ: [u'\n', u'\n', u'\n', u'\n', u... != ['\n', '\n', '\n', '\n', '\n',...

    First differing element 68:
    u','
    '-'

    Diff is 9507 characters long. Set self.maxDiff to None to see it.

    ======================================================================
    FAIL: TableSummarizer functions as expected with qualitative=True
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/tmp.ovLIvfIx3j/tests/test_cli/test_summarize_table.py", line 42, in test_qualitative
        self.assertEqual(sorted(result), sorted(summary_qualitative))
    AssertionError: Lists differ: [u'\n', u'\n', u'\n', u'\n', u... != ['\n', '\n', '\n', '\n', '\n',...

    First differing element 56:
    u','
    '.'
   
    Diff is 7916 characters long. Set self.maxDiff to None to see it.
   
    ----------------------------------------------------------------------
    Ran 308 tests in 31.762s
   
    FAILED (SKIP=1, failures=2)

With Python3 the output is slightly different but the same test is failing:

    $ python3 -m nose tests
    ...
    unzip(items) should be the inverse of zip(*items) ... ok

    ======================================================================
    FAIL: TableSummarizer functions as expected
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/tmp.ovLIvfIx3j/tests/test_cli/test_summarize_table.py", line 33, in test_default
        self.assertEqual(sorted(result), sorted(summary_default))
    AssertionError: Lists differ: ['\n'[355 chars])', ',', ',', ',', ',', ',', ',', ',', ',', ',[1687 chars] 'z'] != ['\n'[355 chars])', '-', '.', '.', '.', '.', '.', '.', '.', '.[1687       chars] 'z']

    First differing element 68:
    ','
    '-'

    Diff is 3455 characters long. Set self.maxDiff to None to see it.

    ======================================================================
    FAIL: TableSummarizer functions as expected with qualitative=True
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/tmp.ovLIvfIx3j/tests/test_cli/test_summarize_table.py", line 42, in test_qualitative
        self.assertEqual(sorted(result), sorted(summary_qualitative))
    AssertionError: Lists differ: ['\n'[293 chars] ', ',', ',', ',', ',', ',', ',', ',', ',', ',[1402 chars] 'y'] != ['\n'[293 chars] ', '.', '.', '.', '.', '.', '.', '.', '.', '.[1402       chars] 'y']

    First differing element 56:
    ','
    '.'

    Diff is 2901 characters long. Set self.maxDiff to None to see it.

    ----------------------------------------------------------------------
    Ran 308 tests in 2.339s

    FAILED (SKIP=1, failures=2)

Any idea how to fix this?
Kind regards, Andreas.

**Comment by wasade** [comment]
Sorry for the delay! I didn't see this issue come by in my inbox. What locale is being used? My gues is that the issue has to deal with representing "1,000" vs. "1.000"?

**Comment by tillea** [comment]
Hi,  thanks a lot for the helpful answer.  Forcing locale setting works so you can probably close this bug.

**Comment by wasade** [comment]
Great, glad to hear!
