### ISSUE TITLE
Example BIOM 1.0 OTU tables note validated by biom validate-table

### ISSUE THREAD

**Issue by gputzel** [biocore/biom-format#779]
The [examples of BIOM 1.0 files](http://biom-format.org/documentation/format_versions/biom-1.0.html) are not validated by `biom validate`, which says, for example:

`Invalid format 'Biological Observation Matrix 0.9.1-dev', must be '1.0.0'`
`Invalid 'format_url'`
`The input file is not a valid BIOM-formatted file.`

**Comment by wasade** [comment]
That is a good find, thank you! We had been testing against the examples [here](https://github.com/biocore/biom-format/tree/master/examples). Would you be interested in submitting a PR to correct the documentation?
