### ISSUE TITLE
The key order of column header is not preserved in biom.load_table object for biom 1.0 file?

### ISSUE THREAD

**Issue by mthang** [biocore/biom-format#781]
Hi there,
I was trying to extract the metadata data table from the biom file (v1.0 - json file) using the feature called metadata() [biom.table.Table.metadata] from this link http://biom-format.org/documentation/generated/biom.table.Table.html .

The feature works just fine, but I noticed that the column header of my metadata table is not in order. Then, I spent a fair amount of time to investigate the metadata feature. However, I realize that there isn't much I can do on this metadata feature.

So, I investigated the following "parse.py" python script (https://github.com/biocore/biom-format/blob/master/biom/parse.py). 

I found the following three main functions and believe that the issue is stemming from the "json.load" in the parse_biom_table function used by load_table function.

- load_table
- parse_biom_table
- json.load

There should be a parameter needs to be added in the json.load which is object_pairs_hook=OrderedDict to preserve the column header in the metadata table. 

For example:
     json.load(handle,object_pairs_hook=OrderedDict)

**Comment by wasade** [comment]
Thanks @mthang. I'd welcome a PR here for this. Do you know if the solution
can be expressed to be py2 and py3 compatible? Note that the Table object
may cast to defaultdict though which might void the parsing type change.

**Comment by mthang** [comment]
I haven't got a chance to test this with python3 yet. It's a good pointer. Thank you !

**Comment by wasade** [comment]
Thank you for this find!
