### ISSUE TITLE
Push biom-format to conda-forge?

### ISSUE THREAD

**Issue by mortonjt** [biocore/biom-format#789]
Since the biocore conda package is out of date, this may be a good opportunity to push the biom package to conda forge: https://github.com/conda-forge

For examples take a look at either 
scikit-bio: https://github.com/conda-forge
emperor: https://github.com/conda-forge/emperor-feedstock

I know that @ElDeveloper and @ebolyen also had some experience with this, so feel free to ask any of us if there are any questions.

**Comment by mortonjt** [comment]
wait derp: has this already been done?

https://github.com/conda-forge/biom-format-feedstock

**Comment by wasade** [comment]
We're in `bioconda`. I'm indifferent to `conda-forge`, will welcome a PR if someone wants to do this but this is low priority for me.

**Comment by mortonjt** [comment]
👍 for bioconda (already forgot about that)
