### ISSUE TITLE
How to add the complete taxonomy level (s) as metadata based on NCBI-taxonomy_id?

### ISSUE THREAD

**Issue by MaryoHg** [biocore/biom-format#796]
Dear biom-format developers,

I have biom files separated by taxon levels (from Phyla to Species = 6 biom files).
The `$biom head -i file.biom` show that first colum is an NCBI id,

|                              |                |                |             |             | 
|------------------------------|----------------|----------------|-------------|-------------| 
| # Constructed from biom file |                |                |             |             | 
| #OTU ID                      | sampleA | SampleB | SampleC | SampleD | 
| 74201                        | 0.00474        | 0.00442        | 0.00303     | 0.00344     | 
| 976                          | 0.016          | 0.01585        | 0.02085     | 0.02533     | 
| 456828                       | 3e-05          | 2e-05          | 1e-05       | 1e-05       | 
| 74152                        | 4e-05          | 4e-05          | 2e-05       | 2e-05       | 
| 201174                       | 0.25734        | 0.25686        | 0.21915     | 0.22133     | 

So, my question is, 
If I want to add the complete taxon level of each "taxonomy_id" as a new column after convert from biom to txt, using: `biom convert -i table.biom -o table.from_biom_w_taxonomy.txt --to-tsv --header-key taxonomy`, even if biom file has no that metadata in first place, 

How can I go through this?
To something like the following table:

| #OTU ID | SampleA | SampleB | SampleC | SampleD | taxonomy                                | 
|---------|----------------|----------------|-------------|-------------|-----------------------------------------| 
| 74201   | 0.00474        | 0.00442        | 0.00303     | 0.00344     | d__Bacteria;p__Verrucomicrobia          | 
| 976     | 0.016          | 0.01585        | 0.02085     | 0.02533     | d__Bacteria;p__Bacteroidetes            | 
| 456828  | 0.00003        | 0.00002        | 0.00001     | 0.00001     | d__Bacteria;p__Candidatus Cloacimonetes | 
| 74152   | 0.00004        | 0.00004        | 0.00002     | 0.00002     | d__Bacteria;p__Elusimicrobia            | 
| 201174  | 0.25734        | 0.25686        | 0.21915     | 0.22133     | d__Bacteria;p__Actinobacteria           | 

I really appreciate any comment or suggestion.
Thanks,

Maryo.

**Comment by wasade** [comment]
Hi Maryo, the convert to a TSV is dependent on the data in the table being converted, and does not have specific knowledge of the NCBI taxonomy. I'm not aware of a command line tool that can consume a tab delimited file, where some column has NCBI taxon IDs, and to fetch the lineage strings. That may be a helpful question to raise on the [QIIME 2 Forum](https://forum.qiime2.org/) though as there may be either good suggestions, or it could make sense as a feature request.

**Comment by MaryoHg** [comment]
@wasade 

I was sure but affraid of this:
> the convert to a TSV is dependent on the data in the table being converted

I appreciate the suggestion.

With regards,

Maryo.
