### ISSUE TITLE
Metadata incorrectly reconstructed in Table.metadata_to_dataframe

### ISSUE THREAD

**Issue by dileep-kishore** [biocore/biom-format#800]
Whenever columns in the metadata are `list`, Eg. after a `Table.collapse` with `include_collapsed_metadata=True`:

```python
(defaultdict(<function biom.table.Table._cast_metadata.<locals>.cast_metadata.<locals>.<lambda>()>,
            {'collapsed_ids': ['otu115']}),
 defaultdict(<function biom.table.Table._cast_metadata.<locals>.cast_metadata.<locals>.<lambda>()>,
             {'collapsed_ids': ['otu95', 'otu175', 'otu127', 'otu30']}),
...
)
```

If I then run `Table.metadata_to_dataframe` it throws an `AssertionError: 1 columns passed, passed data had 4 columns`. I know that this issue happens because of the way `Table.metadata_to_dataframe` behaves here:

https://github.com/biocore/biom-format/blob/29326959151c467c3bac0aff869e76a9e34a8adb/biom/table.py#L4099-L4107

But, the behavior I expect is for the method to just return a `pandas.DataFrame` with a column of `list` objects, or, at least a flag to turn this on.

**Comment by wasade** [comment]
@dileep-kishore, closing for now as more information is needed. Please reopen this issue if it is still a problem.
