### ISSUE TITLE
Issue on big-endian architectures

### ISSUE THREAD

**Issue by tillea** [biocore/biom-format#803]
Hi,
there is a long standing bug open in [Debian bug tracking system](https://bugs.debian.org/820060) which I simply want to document here since there is no sign that this will be solved soon since it seems evident that the issue is caused by [h5py](https://github.com/h5py/h5py/issues/428).  So I open this issue here to get a better connection via Github.
In contrast to what is written in the [Debian bug report](https://bugs.debian.org/820060) you can not see the build logs under the link written there since I have intentionally removed those failing architectures from the list of build targets.
May be we hope and wait for the h5py issue to be solved.
Kind regards, Andreas.

**Comment by wasade** [comment]
It looks like h5py resolved this in 3.0.0 but is not yet available in conda to test against.

**Comment by wasade** [comment]
It looks like h5py/h5py#428 is closed now which I believe resolves this
