### ISSUE TITLE
Convert between Biom 12.1.7 to BIOM 1.0

### ISSUE THREAD

**Issue by ali-kishk** [biocore/biom-format#818]
Hi
I can't find the commands to convert between Biom 12.1.7 to BIOM 1.0

**Comment by wasade** [comment]
Hi @ali-kishk, I don't know what BIOM 12.1.7 is unfortunately...

**Comment by wasade** [comment]
Do you mean converting between the BIOM software package version 2.1.7? That is logically distinct from BIOM-Format 1.0.0, which is a file format and on disk representation of a feature table. The software package (including version 2.1.7) implements the BIOM-Format 1.0.0 specification. More information on the file conversions can be found [here](http://biom-format.org/documentation/biom_conversion.html).
