### ISSUE TITLE
Test issue with pandas1.0

### ISSUE THREAD

**Issue by tillea** [biocore/biom-format#837]
Hi,
the Debian packaged biom-format received a [bug report](https://bugs.debian.org/950929) in connection with pandas 1.0:

    ======================================================================
    ERROR: test_to_dataframe (biom.tests.test_table.TableTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File
    "/build/python-biom-format-2.1.8+dfsg/.pybuild/cpython3_3.8_biom-format/build/biom/tests/test_table.py",
    line 1476, in test_to_dataframe
        exp = pd.SparseDataFrame(np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0]]),
    TypeError: SparseDataFrame() takes no arguments

    ======================================================================
    ERROR: test_to_dataframe_is_sparse (biom.tests.test_table.TableTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File
    "/build/python-biom-format-2.1.8+dfsg/.pybuild/cpython3_3.8_biom-format/build/biom/tests/test_table.py",
    line 1484, in test_to_dataframe_is_sparse
        df = example_table.to_dataframe()
      File
    "/build/python-biom-format-2.1.8+dfsg/.pybuild/cpython3_3.8_biom-format/build/biom/table.py",
    line 4053, in to_dataframe
        return constructor(mat, index=index, columns=columns)
    TypeError: SparseDataFrame() takes no arguments

    ----------------------------------------------------------------------
    Ran 343 tests in 5.493s

Could you please have a look into this?
Kind regards, Andreas.

**Comment by mortonjt** [comment]
@wasade fyi - I'm also able to reproduce this issue in the mmvec tutorials.

**Comment by mr-c** [comment]
Hello. This bug has resulted in biom-format being [removed from Debian's testing distribution](https://tracker.debian.org/news/1172668/python-biom-format-removed-from-testing/), and it is likely to result in complete removal from Debian if not fixed. Any progress on this?

Many thanks,

**Comment by wasade** [comment]
Hi @mr-c, this has been fixed (see this [comment](https://github.com/biocore/biom-format/pull/838#issuecomment-687295879, and commits cf1901c and 87dbdec). I didn't see the cross reference to this issue when working on the other PR, and am closing it now. If I cut a release today, could it be restored in Debian's testing distribution?

**Comment by mr-c** [comment]
@wasade Yes, a new release would be very appreciated! We tried cherry-picking some of those commits, but without everything all together it was too much for us.

**Comment by wasade** [comment]
Okay, great! Sorry for such a delay on this. It's been, you know, a weird few months :)

**Comment by wasade** [comment]
@mr-c, there is at least one more issue I'd like to knock out for this release. I'll ask for expedited review when I get the PR in. I'll send a ping once up on pypi.

**Comment by mr-c** [comment]
No worries @wasade , I understand and I appreciate it!

**Comment by wasade** [comment]
@mr-c, I just pushed [2.1.9](https://github.com/biocore/biom-format/releases/tag/2.1.9) to pypi. Am going to update bioconda shortly.

**Comment by mr-c** [comment]
Huzzah, thank you!
