### ISSUE TITLE
Failed to install with Python2.7

### ISSUE THREAD

**Issue by Nits11** [biocore/biom-format#839]
Hello, I am getting following error with the installation of the package. I have python 2.7 as default on mac10.13.6. I also installed python3.8. But the system is using 2.7 
ERROR: Command errored out with exit status 1:
     command: /opt/anaconda2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5d/t2tsy_7n2_bcjpd_hbpk3v9cnq8bb7/T/pip-install-bw2NuV/biom-format/setup.py'"'"'; __file__='"'"'/private/var/folders/5d/t2tsy_7n2_bcjpd_hbpk3v9cnq8bb7/T/pip-install-bw2NuV/biom-format/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/5d/t2tsy_7n2_bcjpd_hbpk3v9cnq8bb7/T/pip-install-bw2NuV/biom-format/
    Complete output (13 lines):
    /opt/anaconda2/lib/python2.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/5d/t2tsy_7n2_bcjpd_hbpk3v9cnq8bb7/T/pip-install-bw2NuV/biom-format/biom/_filter.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    /opt/anaconda2/lib/python2.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/5d/t2tsy_7n2_bcjpd_hbpk3v9cnq8bb7/T/pip-install-bw2NuV/biom-format/biom/_subsample.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    /opt/anaconda2/lib/python2.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/5d/t2tsy_7n2_bcjpd_hbpk3v9cnq8bb7/T/pip-install-bw2NuV/biom-format/biom/_transform.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    Compiling biom/_filter.pyx because it changed.
    Compiling biom/_transform.pyx because it changed.
    Compiling biom/_subsample.pyx because it changed.
    [1/3] Cythonizing biom/_filter.pyx
    [2/3] Cythonizing biom/_subsample.pyx
    [3/3] Cythonizing biom/_transform.pyx
    Python 2.7 is no longer supported
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by wasade** [comment]
Hi @Nits11, Python 2.7 is no longer supported. If you need to use BIOM-Format within a py27 environment, I recommend using version 2.1.7.
