### ISSUE TITLE
Is it normal that the result of biom add-metadata using v2.1.8 is different from v2.1.7?

### ISSUE THREAD

**Issue by sentausa** [biocore/biom-format#842]
Hi!

(I asked the same question on [StackOverflow](https://stackoverflow.com/questions/62679208/is-it-normal-that-the-result-of-biom-add-metadata-using-v2-1-8-is-different-from) but it's very quiet there; I hope it's OK that I'm cross-posting here).

I'm trying to add sample metadata to a very small BIOM file (658 Bytes, 2 samples) using the command biom add-metadata (the metadata file is 206 Bytes). However, I found that using biom version 2.1.8 resulted in a much bigger file (36.17 KB) than when I used biom version 2.1.7 (615 Bytes). Furthermore, the file created with v2.1.8 does not seem to be a plain text file, as there are many illegible characters when I tried opening it using "more" on terminal or using text editor, while the file created with v2.1.7 is a normal text file.

The machine that I used already has biom v2.1.7, but when I tried to install both v2.1.7 and 2.1.8 using conda, I saw the same behavior. Then I tried to install v2.1.8 using pip (in a conda environment), and still, the difference that I mentioned above is there.

I wonder if this is normal or expected.

Thanks in advance for your input!

**Comment by wasade** [comment]
Hi @sentausa, I apologize for such a delayed response. I suspect what you're seeing is a difference in BIOM-Format 1.0.0 and BIOM-Format 2.1.0. The former is JSON (plain text), and the latter is binary. The formats are, for the majority of use cases, interchangable.
