### ISSUE TITLE
Outputting biom file from dada2 outputs

### ISSUE THREAD

**Issue by sandipansamaddar** [biocore/biom-format#843]
Hi,
I used `dada2` for analyzing the 16S dataset and now I am trying to predict high-level phenotypes in the data using `Bugbase`. But while outputting the biom file I am facing some problems. I am not sure what is going wrong but any help will be appreciated.

`Bugbase` documentation says it needs a OTU table in BIOM format (version 1.0, JSON) picked against a GG database. (https://bugbase.cs.umn.edu/documentation.html)

I used GG database to classify sequences and created a biom file which looks fine to me but its not working and it says not a correct format.

The commands used to generate the biom file were :

In R using `biomformat `package:

```
biom16S <- make_biom(count_tab16s )
biom_file <- biom16S
outfile = tempfile()
write_biom(biom_file, outfile)
```

where count_tab16S is the count file with ASV IDS in rows and sample names in columns.

After getting the output I added the metadata in terminal using the command:

`biom add-metadata -i my.biom -o table-with-taxonomy.biom --observation-metadata-fp taxonomyfile.tsv --sc-separated Taxonomy`

where taxonomyfile.tsv is the file with GG taxonomy information.

After getting the output from the above step I converted the file to JSON:

```
biom convert --table-type="OTU table" -i table-with-taxonomy.biom -o your_OTU_table.txt --to-tsv --header-key taxonomy
biom convert -i your_OTU_table.txt -o OTU_table.biom --table-type="OTU table" --to-json --process-obs-metadata taxonomy
```

I used the output in `Bugbase` but it didnt work.

But when I validated the file using:
`biom validate-table -i OTU_table.biom`

it says its a correctly formatted file.

On the other hand, I also used `Mothur` to process my sequences and created biom file using `make.biom` command and converted file to json the same way I did above but it worked with `Bugbase`.

So I am afraid whats going wrong.

I will also be happy so share any files if needed.

Thanks,

Sandipan

**Comment by wasade** [comment]
Hi @sandipansamaddar, we don't maintain the R biom format package, Bugbase or Mothur. This is the official BIOM-Format reference, so sounds like Bugbase may not be accepting valid BIOM-Format files. Have you opened an issue with them?

**Comment by sandipansamaddar** [comment]
Yes I opened an issue and currently communicating with them. Sorry for populating the space here.

I will post an update when the problem is resolved.

Thank you,

Sandipan

**Comment by wasade** [comment]
Sounds good, thanks!
