### ISSUE TITLE
Feature request: AnnData converesion

### ISSUE THREAD

**Issue by adamgayoso** [biocore/biom-format#844]
Hello,

I'm wondering if there is any interest in adding a feature for a conversion tool from biom data to the [AnnData](https://anndata.readthedocs.io/en/latest/) format. This format is used by many tools for the analysis of single-cell RNA-sequencing data, which to my understanding, can be generally applied to microbiome data (e.g., our tool for dimensionality reduction that @mortonjt [made a tutorial for](https://github.com/mortonjt/scVI/blob/biom/tests/notebooks/biom_tutorial.ipynb)).

It seems like AnnData has the same general structure as biom so I don't believe it should be a difficult addition.

**Comment by wasade** [comment]
@adamgayoso, the support for the scipy sparse objects is identical to the data representation of biom so I agree this probably isn't too bad. Would you be interested in submitting a PR for this? I hesitate to make biom depend on AnnData, however it could be implemented as an optional dependency without too much complexity.
