### ISSUE TITLE
Taxonomy information not retrieve 

### ISSUE THREAD

**Issue by MaryoHg** [biocore/biom-format#852]
Dear all,

I tried to convert a BIOM file using the following code (I usually use it when converting from QIIME ouput to summarize taxonomic levels)

biom convert -i file.biom -o output.tsv --to-tsv --header-key taxonomy`

But when I use the same code on this new file from OneCodex database platform I was not able to retrieve the taxonomy information.

I summarize the table (using `biom summarize-table -i onecodex.biom`) and I get the following information:

> (qiime1) mariohg@Marios-MacBook-Pro BIOM-formats % biom summarize-table -i OneCodexBIOM.biom
> Num samples: 75
> Num observations: 21,263
> Total count: 2,242,340,130
> Table density (fraction of non-zero values): 0.174
> 
> Counts/sample summary:
>  Min: 15,684,383.000
>  Max: 43,642,374.000
>  Median: 29,546,041.000
>  Mean: 29,897,868.400
>  Std. dev.: 5,536,181.251
>  Sample Metadata Categories: library_type; date_collected; location_lon; external_sample_id; name; sample_type; custom; platform; date_sequenced; location_string; starred; location_lat; description
>  Observation Metadata Categories: taxonomy
> 
> Counts/sample detail:
> 3262c45bbe7048a5: 15,684,383.000
> 06fd181984044706: 16,121,189.000
> 3b1b58f024264fb0: 19,694,933.000
> 114949e5bef54858: 21,168,305.000
> 

The option `Observation Metadata Categories: taxonomy` indicates there is indeed taxonomy information, right?

Thanks, and I appreciate any guidance.

MaryoHg

**Comment by wasade** [comment]
Hi @MaryoHg, is any error output produced?

**Comment by MaryoHg** [comment]
@wasade No, no error was produced. However, the last column of the tsv file looks like:

> 
> ff3c40928adb4a89 | b1f5f5514ede474d | taxonomy
> -- | -- | --
> 35438 | 25938 | r; o; o; t
> 2002381 | 3200422 | B; a; c; t; e; r; i; a
> 0 | 0 | C; e; l; l; v; i; b; r; i; o
> 1 | 0 | D; i; c; t; y; o; g; l; o; m; u; s
> 5 | 0 | M; e; t; h; y; l; o; p; h; i; l; u; s
> 0 | 0 | P; h; e; n; y; l; o; b; a; c; t; e; r; i; u; m

So, the taxonomy information is not being retrieve. How can I proceed?


Thanks for your guidance, @wasade.

**Comment by wasade** [comment]
Would it be possible to share the input file with danielmcdonald@ucsd.edu? I suspect the file you received is malformed, but I'd like to verify if possible

**Comment by MaryoHg** [comment]
@wasade Yes, I will send the file to that e-mail.
Thanks for your time.

**Comment by wasade** [comment]
Great, thanks! Or a dropbox link, or something :)

**Comment by MaryoHg** [comment]
Dear Dr. Daniel ( @wasade ), sorry for the delay in response.

I sent an email with the attached file.

I appreciate your time and the effort.


MaryoHg.
