### ISSUE TITLE
ModuleNotFoundError: No module named 'biom'

### ISSUE THREAD

**Issue by arsilan324** [biocore/biom-format#857]
Hi,
I am trying to use [FAPROTAX](https://pages.uoregon.edu/slouca/LoucaLab/archive/FAPROTAX/lib/php/index.php) tool for microbiome function prediction (python script).
I have installed python as well as biom-format but always get this error...

Command I run : `./collapse_table.py -h`

Error message I get:
./collapse_table.py:208: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  return (s.lower() is not 'nan') and is_number(s);
Traceback (most recent call last):
  File "/Users/macair/Documents/qiime2/Soliu16S-revised/FAPROTAX_1.2.4/./collapse_table.py", line 65, in <module>
    import biom
ModuleNotFoundError: No module named 'biom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/macair/Documents/qiime2/Soliu16S-revised/FAPROTAX_1.2.4/./collapse_table.py", line 70, in <module>
    if e.message != 'No module named %s'%(name):
AttributeError: 'ModuleNotFoundError' object has no attribute 'message'

Can you please comment on what is the issue and how can I fix it?
Thanks
Muhammad

**Comment by wasade** [comment]
Hi Muhammad, it looks like the FAPROTAX tool may not be correctly installed. I'm unfamiliar with that tool unfortunately

**Comment by wasade** [comment]
...@arsilan324, I recommend reaching out to the Louca lab (http://www.loucalab.com/archive/FAPROTAX/lib/php/index.php?section=Home) if possible to see what they advise here

**Comment by arsilan324** [comment]
Thanks for the comment. However, FAPROTAX is just python script and there is nothing to install as per my knowledge.

**Comment by wasade** [comment]
Based on the traceback you shared, it appears the tool depends on other things being installed. I recommend contacting the authors of FAPROTAX for assistance. If you'd simply like to install biom, then `pip install biom-format` is one way to do so, however I cannot guarantee that will satisfy the dependency requirements of FAPROTAX
