### ISSUE TITLE
Porting matching functions from gneiss

### ISSUE THREAD

**Issue by mortonjt** [biocore/biom-format#858]
Would there be any interest in porting some of the matching functionality in gneiss?

For instance, there is the situation where one needs to align the sample metadata table against the biom table to make sure that the samples in are in the order.  Or align the tips of a tree against the biom table to make sure that the observations are in the order between the two.  These functions can be very useful for manipulating raw biom tables for classification, as well as performing the ILR transform -- and I have seen this type of functionality reimplemented multiple times across multiple packages, including songbird, mmvec, q2_sample_classifier, q2_diversity many others.

I have a number of functions in gneiss that have been built do this with biom tables.  See [_sparse_match](https://github.com/biocore/gneiss/blob/master/gneiss/util.py#L148) and [_sparse_match_tips](https://github.com/biocore/gneiss/blob/master/gneiss/util.py#L221).   I think these sorts of functions would have a better home in biom than gneiss, since biom is a bit more of a fundamental tool.

**Comment by wasade** [comment]
That would be great!! Would it be possible to issue PRs for this?

**Comment by mortonjt** [comment]
Great, yes let me do that now.

**Comment by wasade** [comment]
Thanks!

**Comment by mortonjt** [comment]
This is addressed by #859
