### ISSUE TITLE
Add flag to relax `remove_empty()`

### ISSUE THREAD

**Issue by mortonjt** [biocore/biom-format#860]
This is a bit of an edge case, but I have a scenario where I don't want to use `remove_empty()` when calling `align_to_dataframe` or `align_tree` -- I just realized this when I was aiming to crunch my large datasets.

This inconvenience largely arises when dealing with multiple biom tables that need to be aligned (i.e. train/valid/test splits need all of the same taxa, even those only present in 1 dataset).

The existing implementation is fine as is, but it would be nice if a `remove_empty` flag was enabled to these two methods to allow for taxa with zero counts to not be filtered out.

**Comment by wasade** [comment]
Does either [`align_to`](https://github.com/biocore/biom-format/blob/master/biom/table.py#L3337), or [`remove_empty(axis='sample')`](https://github.com/biocore/biom-format/blob/master/biom/table.py#L3302) solve the issue?

**Comment by mortonjt** [comment]
Not quite, `align_to` removes a Disjoint ID error -- and `remove_empty` is what we want to avoid, since we want features with zero counts.

Below is the workaround that I was able to construct
```python
train_biom  # biom table that includes all of the features and training data
full biom     # biom table that includes just a subset of training / testing (but is lacking some zero features)
full_biom2 = full_biom.merge(train_biom)
filter_f1 = lambda v, i, m: i in train_biom.ids(axis='observation')
filter_f2 = lambda v, i, m: i in full_biom.ids(axis='sample')
full_biom2.filter(filter_f2, axis='sample')
full_biom2.filter(filter_f1, axis='observation')
# make sure that the ordering of the features is consistent with training dataset
full_biom2.sort_order(train_biom.ids(axis='observation'), axis='observation')
```

Since I'm able to do this with the existing biom API - I believe this issue has been resolved.  If you want to continue brainstorming more streamlined ways to handle zero counts, I guess we can continue that in this thread.
