### ISSUE TITLE
Patch for python3.10 available in Debian

### ISSUE THREAD

**Issue by tillea** [biocore/biom-format#867]
Hi,
I'd like to get you informed that Debian has devloped a [patch](https://salsa.debian.org/med-team/python-biom-format/-/blob/master/debian/patches/python3.10.patch) to support python3.10.  There is a remaining issue with test_from_hdf5_custom_parsers but I will report this in a separate issue.
Hope this helps, Andreas.

**Comment by wasade** [comment]
@tillea sorry for taking so long to circle back on this. I'm unable to recreate this on OS X or Ubuntu (18.04). Specifically, I setup a Python 3.9 environment with h5py 3.5.0 (which seemed to be what was in use in the CI logs). It seems the issue may have been fixed already upstream in h5py? That said, I will implement a variant of this patch that allows the entries test if bytes or utf-8.

**Comment by tillea** [comment]
Hi Daniel,
Am Fri, Mar 25, 2022 at 10:00:46AM -0700 schrieb Daniel McDonald:
> @tillea sorry for taking so long to circle back on this. I'm unable to recreate this on OS X or Ubuntu (18.04).
Ubuntu 18.4 is a bit aged to reproduce the issue.

> Specifically, I setup a Python 3.9 environment with h5py 3.5.0 (which seemed to be what was in use in the CI logs).
The issue is about Python 3.10

> It seems the issue may have been fixed already upstream in h5py?
The issue was about a patch we have just applied in Debian to make biom-format fit for Python 3.10.  So feel free to adapt it.

Kind regards
    Andreas.

**Comment by wasade** [comment]
Hi was confused about that :) I thought it was py 3.10 based on the discussion, however the build log you had linked shows py 3.9 (https://salsa.debian.org/med-team/python-biom-format/-/jobs/2209227#L2815)

**Comment by wasade** [comment]
Either way, the relaxation of the unit test should fix it afaik

**Comment by tillea** [comment]
Am Fri, Mar 25, 2022 at 03:56:16PM -0700 schrieb Daniel McDonald:
> Either way, the relaxation of the unit test should fix it afaik
Ahh, you were right it is 3.9 as well - but you are right there is a solution.
