### ISSUE TITLE
AssertionError: 'GUT' not found in (b'GUT', b'SKIN')

### ISSUE THREAD

**Issue by tillea** [biocore/biom-format#868]
Hi,
as I wrote in issue #867 there is a remaining test failure:

    ___________________ TableTests.test_from_hdf5_custom_parsers ___________________
    self = <biom.tests.test_table.TableTests testMethod=test_from_hdf5_custom_parsers>
        @pytest.mark.skipif(HAVE_H5PY is False, reason='H5PY is not installed')
        def test_from_hdf5_custom_parsers(self):
            def parser(item):
                return general_parser(item).upper()
            parse_fs = {'BODY_SITE': parser}
    
            cwd = os.getcwd()
            if '/' in __file__:
                os.chdir(__file__.rsplit('/', 1)[0])
            t = Table.from_hdf5(h5py.File('test_data/test.biom'),
                                parse_fs=parse_fs)
            os.chdir(cwd)
    
            for m in t.metadata():
    >           self.assertIn(m['BODY_SITE'], (b'GUT', b'SKIN'))
    E           AssertionError: 'GUT' not found in (b'GUT', b'SKIN')
    /builds/med-team/python-biom-format/debian/output/source_dir/.pybuild/cpython3_3.9_biom-format/build/biom/tests/test_table.py:661: AssertionError

There is a [full build log](https://salsa.debian.org/med-team/python-biom-format/-/jobs/2209227#L2736) in our CI infrastructure in case you might wonder what version of h5py is used.
Kind regards, Andreas.

**Comment by wasade** [comment]
As noted in #867, I'm unable to recreate this issue however I'll be relaxing the test to allow for bytes or unicode
