### ISSUE TITLE
When a osx-arm64 build ?

### ISSUE THREAD

**Issue by borexino** [biocore/biom-format#890]
Refering to this [picrust2 issue](https://github.com/picrust/picrust2/issues/287#issuecomment-1319788419) I'm wandering if  biom-format `osx-arm64 build` will be released soon or, if there's something that I can do to solve this annoying problem.
Thanks

**Comment by wasade** [comment]
Would you be interested in submitting a pull request to the conda-forge biom-format recipe? Looks like information about osx-arm64 is [here](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/). The specific recipe file is [here](https://github.com/conda-forge/biom-format-feedstock/blob/main/recipe/meta.yaml)
