### ISSUE TITLE
pip check reports cython as a requirement

### ISSUE THREAD

**Issue by Midnighter** [biocore/biom-format#898]
I have a [bioconda package](https://github.com/bioconda/bioconda-recipes/pull/39809) that depends on biom-format. Among its tests is a `pip check` which reports cython as missing.

I see two possible solution:

1. Add cython to the [conda-forge biom-format](https://github.com/conda-forge/biom-format-feedstock) feedstock as a run dependency. I think, this is the worse solution.
2. Remove cython from the `install_requires`. You already list it in `pyproject.toml` and cython is imported by `setup.py` itself. So at that point it's too late to install the requirement anyway. I consider this the better option. Unless, of course, cython is truly needed at runtime but I don't see why that would be the case.

**Comment by wasade** [comment]
Thanks, @Midnighter! This is a historical carryover from very early in the project where managing Cython code was a bit different. I agree that (2) is a much better way to go about it.

How urgent is this?

**Comment by Midnighter** [comment]
I've disabled the pip check for now in order to proceed with the recipe.

Since it's a pretty small change, I can also create a PR for it if you like.

**Comment by wasade** [comment]
Oh, that would be really helpful, thank you!
