### ISSUE TITLE
Sample metadata handled differently by implementations

### ISSUE THREAD

**Issue by chrysn** [biocore/biom-format#925]
Exchanging data in the biom format between Python (using the biom-format package) and R (using [rbiom](https://github.com/cmmr/rbiom)) is using different and incompatible formats:

* On the Python side, taxonomy is typically stored in metadata on the observation axis (eg. in [test_cli/test_summarize_table.py](https://github.com/biocore/biom-format/blob/166d2dd446df5a67738e6c1f06b5ec19d86be9af/biom/tests/test_cli/test_summarize_table.py): ` "metadata": {"taxonomy": ["k__Bacteria"]}`).

  That data appears to be unavailable when loading the biom file through rbiom.

* From R, taxonomy data is feature of its own, and data stored in `biom$taxonomy` appears not to be exposed when loading the biom file in Python.

(All my tests I've done with the h5 storage format.)

I'm not sure whether this is a matter of implementation shortcomings or lack of clarity in the specification; if it is the former (and the rbiom package is the one that got it wrong), I'd appreciate any pointer inside the specification I could use when opening a replacement issue on the rbiom side.

**Comment by wasade** [comment]
Hi @chrysn,

Thank you for opening this issue, and I'm sorry to learn about the inconsistency. On the surface, it sounds like there may be a different interpretation of the format. This repository is the official BIOM implementation, and the format specification the HDF5 container can be found [here](http://biom-format.org/documentation/format_versions/biom-2.1.html). 

If you do decide to open an issue with `rbiom`, could you tag me and cross reference this issue? Cross language interoperability is extremely important, and while I'm unaffiliated with `rbiom`, I'd be eager to work with them to normalize processing.

**Comment by wasade** [comment]
@chrysn, please re-open this issue if it is still relevant. If an issue was opened with `rbiom`, it would be helpful to cross reference it here.
