### ISSUE TITLE
Trouble with installation using pip

### ISSUE THREAD

**Issue by UmaJan** [biocore/biom-format#941]
Attempting installation on cluster using pip install results in "failure to build wheel" messag repeatedly.

**Comment by wasade** [comment]
Hi @UmaJan, can you confirm what version of python and share the full output you're receiving?

**Comment by UmaJan** [comment]
I am using 3.1 and am getting these messages 
![image](https://github.com/biocore/biom-format/assets/57330193/913a721c-898b-4cbc-97d6-6670ab712f89) 
![image](https://github.com/biocore/biom-format/assets/57330193/1f240b6b-17ea-44f1-8bde-0a3c7d6c4c5f)

   error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for biom-format
Failed to build biom-format
ERROR: Could not build wheels for biom-format, which is required to install pyproject.toml-based projects

**Comment by sfiligoi** [comment]
Maybe it should be documented, but looks like the recipe expects you to have a valid compiler installed.

Can you retry after installing separately the usual compiler environment:
gcc, g++, make

**Comment by wasade** [comment]
Hi @UmaJan, we have not verified support for Python 3.12 yet, and also do not currently provide pre-built wheels for Python 3.12. You can find the versions we test against [here](https://github.com/biocore/biom-format/blob/master/.github/workflows/python-package-conda.yml#L13). 

Are you required to use Python 3.12 or can you instead use 3.11?

**Comment by UmaJan** [comment]
I am using 3.6.8 currently I will try with some of the tested versions

**Comment by wasade** [comment]
Okay, but the screenshots show Python 3.12. We dropped support for 3.6 a bit ago. Please let us know how things proceed!

**Comment by UmaJan** [comment]
> know

I switched to pyenv and used a 3.7 shell and it works, thanks!

**Comment by wasade** [comment]
That's great! Sorry for the issues and glad it's working now!
