### ISSUE TITLE
align_tree cannot handle features with 0 counts

### ISSUE THREAD

**Issue by dpear** [biocore/biom-format#948]
if a feature table has a feature with 0 sum, align_tree will throw an error stating that the id of the feature is not present in the table. (apologies for brevity, let me know and I can follow up with code examples etc.)

**Comment by wasade** [comment]
Thanks, @mortonjt! But there is an edge case here that needs to be fixed. `sort_order` based off the tree, but called after `remove_empty` which will raise if a feature is removed.

**Comment by wasade** [comment]
Fixed in #959, unsure why it didn't automatically close.
